#ifndef AMSENUM_H
#define AMSENUM_H


#define AMS_COMMON_REASON_BASE                            0X0000
#define AMS_CRM_QUEUE_MNG_REASON_BASE                     0X1000
#define AMS_TERM_MNG_REASON_BASE                           0X5000
#define AMS_CALL_REASON_BASE                              0X7000


#define AMS_SERVICE_RSVD_VALUE                            0XFFFFFFFF

enum amsCallEventIndCode
{
	AMS_CALL_EVENT_IND_RSVD                   = 0,
		
	AMS_CALL_EVENT_IND_TELLER_ERR             = 1,
	AMS_CALL_EVENT_IND_TELLER_FORCELOGOUT     = 2,
	AMS_CALL_EVENT_IND_TELLER_LOGOUT          = 3,

	AMS_CALL_EVENT_IND_MAX,
};

enum amsTellerEventNoticeCode
{
	AMS_TELLER_EVENT_NOTICE_RSVD                = 0,

	AMS_TELLER_ROBOT_TEST_ERR                   = 1,
	AMS_TELLER_HUMAN_TEST_ERR                   = 2,
	
	AMS_TELLER_EVENT_NOTICE_MAX,
};


enum amsTellerQueryInfoType
{
	AMS_CRM_QUERY_CRM_INFO_RSVD                = 0,
	AMS_CRM_QUERY_ALL_TELLER_STATE_INFO        = 1,	
	AMS_CRM_QUERY_TELLER_STATE_INFO            = 2,	
	AMS_CRM_QUERY_TELLER_SERVICE_LIST          = 3,	
	AMS_CRM_QUERY_SERVICE_TELLER_LIST          = 4,	
	AMS_CRM_QUERY_SERVICE_QUEUE_INFO           = 5,	
	AMS_CRM_QUERY_SERVICE_GROUP_ID_QUEUE_INFO  = 6,		
	AMS_CRM_QUERY_CUR_TELLER_SERVICE_LIST      = 7,	
	AMS_CRM_QUERY_CUR_TELLER_WORK_CALINFO      = 8,
	AMS_CRM_QUERY_CUR_TELLER_WORK_INFO         = 9,		
	AMS_CRM_QUERY_TELLER_LIST_BY_NO_KEY        = 10,		
	AMS_CRM_QUERY_TELLER_LIST_BY_NAME_KEY      = 11,
	AMS_CRM_QUERY_TELLER_LIST_BY_NICKNAME_KEY  = 12,
	
	AMS_CRM_QUERY_TYPE_MAX,
};


enum amsTermType_t
{
	AMS_TERM_TYPE_RESVD = 0,

	AMS_TERM_TYPE_ROBOT   = 1,
	AMS_TERM_TYPE_TELLER  = 2,
	AMS_TERM_TYPE_MBPHONE = 3,
	AMS_TERM_TYPE_PC      = 4,

	AMS_TERM_TYPE_MAX,
};


enum amsMsgType_t
{
	AMS_MSG_TYPE_NULL = 0,
	AMS_CRM_MSG,
	AMS_TERM_MSG,
	AMS_CMS_MSG,
	AMS_RCAS_MSG,

	AMS_B_MSG,
	AMS_C_MSG,
	
	AMS_OTHER_MSG_TYPE,
};

enum amsStateType
{
	AMS_STATE_NULL = 0,
	AMS_CRM_STATE,		
	AMS_CALL_STATE,
	AMS_TERM_STATE,
	AMS_CUSTOMER_STATE,
};


enum amsStatType_t
{
	AMS_STAT_TYPE_NULL = 0,

	AMS_MSG_STAT_TYPE,
	AMS_TIMER_STAT_TYPE,
	
	AMS_TELLER_STAT_TYPE,
	AMS_RESULT_STAT_TYPE,
	
	AMS_STAT_TYPE_MAX,
};


enum amsTermState
{
	AMS_TERM_STATE_IDLE = 0,
	AMS_TERM_STATE_BUSY,
	AMS_TERM_STATE_OFFLINE,

	AMS_TERM_STATE_RSVD
};

enum amsCustomerServiceState
{
	AMS_CUSTOMER_SERVICE_NULL                  = 0,

	AMS_CUSTOMER_IN_QUEUE                      = 1,
	AMS_CUSTOMER_IN_SERVICE                    = 2,	

	AMS_CUSTOMER_SERVICE_RSVD,
};


enum amsOParaId_t
{
	AMS_TELLER_PERSIONALDATA_ID   = 0X01,	
	AMS_STATE_OP_INFO_ID          = 0x02,
	AMS_TERM_NET_INFO_ID          = 0x03,
	AMS_LOGIN_STATE_ID            = 0x04,
	AMS_CALL_RELL_STATE_ID        = 0x05,
	AMS_ANSWER_TYPE_ID            = 0x06,
	AMS_TELLER_STATE_INFO_ID      = 0x10,
	AMS_QUEUE_INFO_ID             = 0x11,
	AMS_TELLER_WORK_STAT_ID       = 0x12,
	AMS_TELLER_WORK_SHEET_ID      = 0x13,
	AMS_SERVICE_LIST_ID           = 0x14,
	AMS_TELLER_LIST_ID            = 0x15,
	AMS_CRM_LOGIN_ERR_ID          = 0x16,
};

enum amsTimerType_t
{
	T_AMS_TIMER_NULL = 0,

	T_AMS_CUSTOMER_IN_QUEUE_TIMER,
	T_AMS_CRM_STATE_OPERATE_IND_TIMER,
	T_AMS_REST_TIMER,
	
	T_AMS_TIMER_MAX,
};


enum amsTimerStatType_t
{
	AMS_CREATE_TIMER = 0,
	AMS_KILL_TIMER,
	AMS_TIMER_TIMEOUT,
};

enum amsTellerType_t
{
	AMS_TELLER_RSVD								= 0,
	AMS_TELLER_ROBOT							= 1,
	AMS_TELLER_TELLER							= 2,
	AMS_TELLER_MANAGER							= 3,
	AMS_TELLER_INSPECTOR						= 4,
	AMS_TELLER_MAX,
};

enum amsSrvGrpAutoFlag
{
	AMS_SRVGRP_RSVD								= 0,
		
	AMS_SRVGRP_TYPE_AUTO						= 1,
	AMS_SRVGRP_TYPE_HUMAN						= 2,
	
	AMS_SRVGRP_TYPE_MAX,
};


enum cmsCallEventNoticeCode
{
	CMS_CALL_EVENT_NOTICE_RSVD                  = 0,

	CMS_CALL_EVENT_NOTICE_CRM_RING              = 1,
	CMS_CALL_EVENT_NOTICE_CRM_ANSWER            = 2,
	CMS_CALL_EVENT_NOTICE_CRM_RELEASE           = 3,
	CMS_CALL_EVENT_NOTICE_TERM_RING	            = 10,
	CMS_CALL_EVENT_NOTICE_TERM_ANSWER            = 11,
	CMS_CALL_EVENT_NOTICE_TERM_RELEASE           = 12,
	
	CMS_CALL_EVENT_NOTICE_MAX,
};



enum crmStateOperateCode
{
	CRM_STATE_OPERATE_RSVD                     = 0,

	CRM_STATE_OPERATE_IDLE                     = 1,
	CRM_STATE_OPERATE_BUSY                     = 2,
	CRM_STATE_OPERATE_REST					   = 3,
	CRM_STATE_OPERATE_PREPARE                  = 4,
	
	CRM_STATE_OPERATE_MAX,
};


enum amsTellerStatType_t
{
	AMS_TELLER_STAT_TYPE_NULL = 0,

	AMS_TELLER_LOGIN,
	AMS_TELLER_LOGOUT,
	AMS_TELLER_HANDSHAKE,
	
	AMS_TELLER_SET_IDLE,
	AMS_TELLER_SET_BUSY,
	AMS_TELLER_SET_REST,
	AMS_TELLER_SET_CANCEL_REST,	
	AMS_TELLER_SET_PREPARA,
	AMS_TELLER_SET_PREPARA_COMPLETELY,

	AMS_TELLER_CALL_CONNECT,
	AMS_TELLER_CALL_TRANSFER,
	AMS_TELLER_INNER_CALL,
	
	AMS_TELLER_VOLUME_CTRL,
	AMS_TELLER_AUDIO_RECORD,
	AMS_TELLER_SCREEN_RECORD,
	AMS_TELLER_REMOTE_COOPERATE,
	AMS_TELLER_SNAP,

	AMS_TELLER_WORK_INFO_AFTER_LOGINED,
	
	AMS_TELLER_SCORE_INFO,

	AMS_TELLER_LAST_STATE_INFO,

	AMS_TELLER_STAT_TYPE_MAX,
	
};

enum amsVtcTellerState
{	
	AMS_VTC_TELLER_STATE_IDLE                  = 0,
	AMS_VTC_TELLER_STATE_QUEUING               = 1,		
	AMS_VTC_TELLER_STATE_RINGING               = 2,
	AMS_VTC_TELLER_STATE_ANSWER                = 3,
	AMS_VTC_TELLER_STATE_BUSY                  = 4,
	AMS_VTC_TELLER_STATE_PREPARE               = 5,
	AMS_VTC_TELLER_STATE_REST                  = 6,
	AMS_VTC_TELLER_STATE_OFFLINE               = 7,	
	
	AMS_VTC_TELLER_STATE_RSVD,
};


enum amsCrmState
{
	AMS_CRM_STATE_IDLE = 0,
	AMS_CRM_STATE_BUSY,
	AMS_CRM_STATE_REST,
	AMS_CRM_STATE_PREPARE,
	AMS_CRM_STATE_OFFLINE,
//	AMS_CRM_STATE_LEAVE,
	
	AMS_CRM_STATE_RSVD,  	//AMS_CRM_STATE_RSVD 5
};


enum amsCallState
{
	AMS_CALL_STATE_NULL = 0,
	AMS_CALL_STATE_WAIT_ANSWER,
	AMS_CALL_STATE_TRANSFER,
	AMS_CALL_STATE_ANSWER,
	AMS_CALL_STATE_HOLD,	
	AMS_CALL_STATE_INNER_CALL,
	AMS_CALL_STATE_MONITOR_CALL,
	AMS_CALL_STATE_CONF,

	AMS_CALL_STATE_RSVD,  //AMS_CALL_STATE_RSVD 6

};


enum crmStateOperateIndCode
{
	CRM_STATE_OPERATE_IND_RSVD                 = 0,
		
	CRM_STATE_OPERATE_IND_IDLE                 = 1,
	CRM_STATE_OPERATE_IND_BUSY                 = 2,
	CRM_STATE_OPERATE_IND_REST                 = 3,
	CRM_STATE_OPERATE_IND_PREPARE              = 4,
	
	CRM_STATE_OPERATE_IND_MAX,
};

enum crmStateOperateIndIdleCode
{
	CRM_STATE_OPERATE_IND_IDLE_RSVD				= 0,
	CRM_STATE_OPERATE_IND_IDLE_IND				= 1,
	CRM_STATE_OPERATE_IND_IDLE_REL				= 2,
	CRM_STATE_OPERATE_IND_IDLE_REST_TIMEOUT		= 3,

	CRM_STATE_OPERATE_IND_IDLE_MAX,
};

enum crmStateOperateIndBusyCode
{
	CRM_STATE_OPERATE_IND_BUSY_RSVD				= 0,

	CRM_STATE_OPERATE_IND_BUSY_IND				= 1,
	CRM_STATE_OPERATE_IND_BUSY_CALLOUTSOLO		= 2,
	CRM_STATE_OPERATE_IND_BUSY_CALLOUTDB		= 3,
	CRM_STATE_OPERATE_IND_BUSY_RING				= 4,
	CRM_STATE_OPERATE_IND_BUSY_ANSWER			= 5,

	CRM_STATE_OPERATE_IND_BUSY_MAX,
};

enum amsServiceGroupFlag
{
	AMS_SERVICE_GROUP_UNINSTALL              = 0,
	AMS_SERVICE_GROUP_INSTALL                = 1,	
};

enum amsServiceState
{
	AMS_SERVICE_INACTIVE = 0,
	AMS_SERVICE_ACTIVE,
};

enum amsServiceFlag
{
	AMS_SERVICE_UNINSTALL                    = 0,
	AMS_SERVICE_INSTALL                      = 1,	
};

enum amsTellerServiceFlag
{
	AMS_TELLER_UNINSTALL                     = 0,
	AMS_TELLER_INSTALL                       = 1,
};


enum amsTellerRegisterFlag
{
	AMS_TELLER_UNREGISTER                    = 0,
	AMS_TELLER_REGISTER                      = 1,
};


enum amsTermFlag
{
	AMS_TERM_UNINSTALL                        = 0,
	AMS_TERM_INSTALL                          = 1,
};

enum amsQueueFlag
{
	AMS_QUEUE_NOT_CFG                        = 0,
	AMS_QUEUE_CFG                            = 1,
};


enum amsCommonResult
{
	AMS_SUCCESS = AMS_COMMON_REASON_BASE,
	AMS_PARA_ERR,
	AMS_STATE_ERR,
	AMS_ALLOC_MEM_FAILED,
	AMS_ALLOC_LP_FAILED,
	AMS_ALLOC_LT_FAILED,

	AMS_PARA_CFG_INF_CNF_TIMEOUT = 0x001f,
	
	AMS_OTHER_FAILED             = 0x00ff,
};

enum amsResultType_t
{
	AMS_COMMON_RESULT = 0,

	AMS_CRM_LOGIN_RESULT,
	AMS_CRM_LOGOUT_RESULT,
	AMS_CRM_STATE_OPERATE_RESULT,
	AMS_CRM_MODIFY_PASSWORD_RESULT,
	AMS_CRM_FORCE_LOGIN_RESULT,	
	AMS_CRM_QUERY_INFO_RESULT,
	AMS_MANAGER_SET_CRM_STATE_RESULT,	

	AMS_CRM_EVENT_NOTICE_RESULT,
	
	AMS_CMS_CRM_REG_RESULT,
	AMS_CMS_GET_CRM_RESULT,
	AMS_CMS_CRM_CALLOUT_RESULT,
	AMS_CMS_CRM_AUTHINFO_RESULT,
	AMS_CMS_EVENT_NOTICE_RESULT,
	AMS_CMS_EVENT_IND_RESULT,

	AMS_OTHER_RESULT_TYPE,
};


enum amsCmsProcessResult
{
	AMS_CMS_PRCOESS_SUCCESS = 0,

	AMS_CMS_CRM_REG_PARA_ERR = AMS_CALL_REASON_BASE,
	AMS_CMS_CRM_REG_STATE_ERR,
	AMS_CMS_CRM_REG_LEN_ERR,	
	AMS_CMS_CRM_REG_TELLER_ID_ERR,	
	AMS_CMS_CRM_REG_RESOURCE_LIMITED,
	
	AMS_CMS_GET_CRM_PARA_ERR = (0x0200 + AMS_CALL_REASON_BASE), //0x0200
	AMS_CMS_GET_CRM_LEN_ERR,	
	AMS_CMS_GET_CRM_AMS_PID_ERR,
	AMS_CMS_GET_CRM_CALL_ID_ERR,
	AMS_CMS_GET_CRM_TERMINAL_TYPE_ERR,	 
	AMS_CMS_GET_CRM_SERVICE_GROUP_ID_ERR,	
	AMS_CMS_GET_CRM_SERVICE_TYPE_ERR,
	AMS_CMS_GET_CRM_NO_VALID_SERVICE_GROUP_ID_OR_TYPE,
	AMS_CMS_GET_CRM_TERM_ID_ERR,
	AMS_CMS_GET_CRM_SRVGRP_ID_ERR,
	AMS_CMS_GET_CRM_SRVTYPE_ERR,
	AMS_CMS_GET_CRM_TERM_RESOURCE_LIMITED,
	AMS_CMS_GET_CRM_VALID_SRVTYPE_OR_SRVGRPID,

	AMS_CMS_GET_CRM_LICENSE_TIMEOUT, //LIC
	AMS_CMS_GET_CRM_TPS_BEYOND_LIC,//LIC
	
	AMS_CMS_GET_CRM_SERVICE_IN_QUEUE = (0x0300 + AMS_CALL_REASON_BASE),//0x0300 0x7300
	AMS_CMS_GET_CRM_SERVICE_INTELLIGENT_ROUTING_ERR,
	
	AMS_CMS_GET_CRM_SIR_TERMNO_ERR,// SIR SERVICE_INTELLIGENT_ROUTING
	AMS_CMS_GET_CRM_SIR_SERVICE_GROUP_ID_ERR,
	AMS_CMS_GET_CRM_SIR_CALL_TYPE_ERR,
	AMS_CMS_GET_CRM_SIR_CRM_EMPTY,
	AMS_CMS_GET_CRM_SIR_CALC_QUEUE_INFO_ERR,
	AMS_CMS_GET_CRM_SIR_TOO_MANY_CUSTOMER_IN_QUEUE, 
	AMS_CMS_GET_CRM_SIR_TARGET_TELLER_NOT_LOGIN,
	AMS_CMS_GET_CRM_SIR_TARGET_TELLER_NOT_REGISTERED,
	AMS_CMS_GET_CRM_SIR_TARGET_TELLER_STATE_ERR,
	AMS_CMS_GET_CRM_SIR_CALL_TRANSFER_TOO_MANY_TIMES,
	AMS_CMS_GET_CRM_ORG_ID_ERR,
	AMS_CMS_GET_CRM_ORG_POS_ERR,
	AMS_CMS_GET_CRM_PARENT_ORG_ID_ERR,
	AMS_CMS_GET_CRM_SELECT_SERVICE_GROUP_ID_ERR,
	
	AMS_CMS_GET_CRM_LP_RESOURCE_LIMITED,
	AMS_CMS_GET_CRM_CREATE_TIMER_ERR,
	AMS_CMS_GET_CRM_TIMEOUT,
	
	AMS_CMS_GET_CRM_TIMEOUT_PARA_ERR = (0x0400 + AMS_CALL_REASON_BASE),
	AMS_CMS_GET_CRM_TIMEOUT_STATE_ERR,
	AMS_CMS_GET_CRM_TIMEOUT_LEN_ERR,		
	AMS_CMS_GET_CRM_TIMEOUT_TERM_ID_ERR,
	AMS_CMS_GET_CRM_TIMEOUT_SERVICE_STATE_ERR,

	
	AMS_CMS_CALLOUT_PARA_ERR        = (0x0500 + AMS_CALL_REASON_BASE),
	AMS_CMS_CALLOUT_CRM_CALL_ID_ERR,
	AMS_CMS_CALLOUT_CRM_TELLER_ID_ERR,
	AMS_CMS_CALLOUT_CRM_SRVGRP_ID_ERR,
	AMS_CMS_CALLOUT_CRM_SRVTYPE_ERR,
	AMS_CMS_CALLOUT_CRM_TELLER_ID_NOTCFG_ERR,
	AMS_CMS_CALLOUT_CRM_TELLER_ID_NOT_REG_ERR,
	AMS_CMS_CALLOUT_CRM_TELLER_ID_NOTLOGIN_ERR,
	AMS_CMS_CALLOUT_AMS_PID_ERR,
	AMS_CMS_CALLOUT_CRMREPEAT_ERR,
	AMS_CMS_CALLOUT_STATE_ERR,
	
	
	AMS_CMS_AUTHINFO_PARA_ERR       = (0X0600 + AMS_CALL_REASON_BASE),
	AMS_CMS_AUTHINFO_TELLER_ID_LEN_ERR,
	AMS_CMS_AUTHINFO_TELLER_ID_NOTCFG_ERR,
	AMS_CMS_AUTHINFO_TELLER_ID_REPEAT_ERR,
	
	
	AMS_CMS_EVENT_NOTICE_PARA_ERR = (0x0700 + AMS_CALL_REASON_BASE),
	AMS_CMS_EVENT_NOTICE_STATE_ERR, 
	AMS_CMS_EVENT_NOTICE_SERVICE_GROUP_ID_ERR, 
	AMS_CMS_EVENT_NOTICE_SERVICE_STATE_ERR, 
	AMS_CMS_EVENT_NOTICE_LEN_ERR,
	AMS_CMS_EVENT_NOTICE_AMS_PID_ERR,
	AMS_CMS_EVENT_NOTICE_CALL_ID_ERR,	
	AMS_CMS_EVENT_NOTICE_TELLER_ID_ERR,
	AMS_CMS_EVENT_NOTICE_TERM_ID_ERR,
	AMS_CMS_EVENT_NOTICE_CODE_ERR,
	AMS_CMS_EVENT_NOTICE_CRM_STATE_ERR,
	AMS_CMS_EVENT_NOTICE_TERM_STATE_ERR,	
	
	AMS_CMS_EVENT_NOTICE_ORIGIN_TELLER_ID_ERR,
	AMS_CMS_EVENT_NOTICE_ORIGIN_TELLER_STATE_ERR,
	AMS_CMS_EVENT_NOTICE_ORIGIN_TELLER_AMS_PID_ERR,
	AMS_CMS_EVENT_NOTICE_ORIGIN_TELLER_SERVICE_GROUP_ID_ERR,
	AMS_CMS_EVENT_NOTICE_ORIGIN_TELLER_SERVICE_STATE_ERR,

	AMS_CMS_HANDSHAKE_CLEAR_INACTIVTE_CALL,
	
	AMS_CMS_EVENT_IND_CNF_PARA_ERR = (0x0800 + AMS_CALL_REASON_BASE),
	AMS_CMS_EVENT_IND_CNF_STATE_ERR, 
	AMS_CMS_EVENT_IND_CNF_LEN_ERR,
	AMS_CMS_EVENT_IND_CNF_AMS_PID_ERR,
	AMS_CMS_EVENT_IND_CNF_CALL_ID_ERR,
	AMS_CMS_EVENT_IND_CNF_TELLER_ID_ERR,
	AMS_CMS_EVENT_IND_CNF_TERM_ID_ERR,	
	AMS_CMS_EVENT_IND_CNF_TELLER_STATE_ERR,	
	AMS_CMS_EVENT_IND_CNF_TELLER_UPDATE_STATE_ERR,		
	AMS_CMS_EVENT_IND_CNF_TERM_STATE_ERR,	
	AMS_CMS_EVENT_IND_CNF_CODE_ERR,
	AMS_CMS_EVENT_IND_CNF_CMS_REPORT_FAIL,

	AMS_CMS_EVENT_IND_TIMEOUT_PARA_ERR = (0x0740  + AMS_CALL_REASON_BASE),
	AMS_CMS_EVENT_IND_TIMEOUT_STATE_ERR, 
	AMS_CMS_EVENT_IND_TIMEOUT_LEN_ERR,
	AMS_CMS_EVENT_IND_TIMEOUT_AMS_PID_ERR,
	AMS_CMS_EVENT_IND_TIMEOUT_CALL_ID_ERR,
	AMS_CMS_EVENT_IND_TIMEOUT_TELLER_ID_ERR,
	AMS_CMS_EVENT_IND_TIMEOUT_TERM_ID_ERR,	
	AMS_CMS_EVENT_IND_TIMEOUT_TELLER_STATE_ERR,		
	AMS_CMS_EVENT_IND_TIMEOUT_TERM_STATE_ERR,	
	AMS_CMS_EVENT_IND_TIMEOUT_CODE_ERR,	
	AMS_CMS_EVENT_IND_TIMEOUT_SERVICE_GROUP_ID_ERR,	
	AMS_CMS_EVENT_IND_TIMEOUT_SERVICE_STATE_ERR,	

	AMS_CMS_PROCESS_OTHER_FAIL = (0x0fff  + AMS_CALL_REASON_BASE), //0x7fff

};



enum amsCrmQueueMngResult
{
	AMS_CRM_QUEUE_MNG_SUCCESS = 0,

	AMS_CRM_LOGIN_PARA_ERR = AMS_CRM_QUEUE_MNG_REASON_BASE,
	AMS_CRM_LOGIN_PID_ERR,
	AMS_CRM_LOGIN_NODE_RESOURCE_LIMITED,
	AMS_CRM_LOGIN_TELLER_LEN_ERR,	
	AMS_CRM_LOGIN_TELLER_NO_ERR,
	AMS_CRM_LOGIN_TELLER_PWD_ERR,
	AMS_CRM_LOGIN_TELLER_LOGIN_REPEATEDLY,
	AMS_CRM_LOGIN_TELLER_NUM_ERR,
	AMS_CRM_LOGIN_LP_RESOURCE_LIMITED,
	AMS_CRM_LOGIN_TELLER_LOGIN_NOTREGSITER,
	
	AMS_CRM_LOGOUT_PARA_ERR = (0x0100 + AMS_CRM_QUEUE_MNG_REASON_BASE),
	AMS_CRM_LOGOUT_STATE_ERR, 
	AMS_CRM_LOGOUT_LEN_ERR,
	AMS_CRM_LOGOUT_AMS_PID_ERR,
	AMS_CRM_LOGOUT_TELLER_ID_ERR,
	AMS_CRM_LOGOUT_SERVICE_GROUP_ID_ERR, 
	AMS_CRM_LOGOUT_SERVICE_STATE_ERR, 
	
	AMS_CRM_STATE_OPERATE_PARA_ERR = (0x0300 + AMS_CRM_QUEUE_MNG_REASON_BASE),
	AMS_CRM_STATE_OPERATE_STATE_ERR, 
	AMS_CRM_STATE_OPERATE_LEN_ERR,	
	AMS_CRM_STATE_OPERATE_AMS_PID_ERR,
	AMS_CRM_STATE_OPERATE_TELLER_ID_ERR,
	AMS_CRM_STATE_OPERATE_SERVICE_GROUP_ID_ERR, 	
	AMS_CRM_STATE_OPERATE_SERVICE_STATE_ERR, 	
	AMS_CRM_STATE_OPERATE_CODE_ERR,
	AMS_CRM_STATE_OPERATE_STATE_OP_REASON_ERR,
	AMS_CRM_STATE_OPERATE_STATE_OP_TIMELEN_ERR,
	AMS_CRM_STATE_OPERATE_UPDATE_STATE_ERR, 	
	AMS_CRM_STATE_OPERATE_START_TIMER_ERR,
	AMS_CRM_STATE_OPERATE_REST_TIMEOUT,
	
	AMS_CRM_STATE_OPERATE_REST_TIMEOUT_PARA_ERR = (0x0340 + AMS_CRM_QUEUE_MNG_REASON_BASE),
	AMS_CRM_STATE_OPERATE_REST_TIMEOUT_STATE_ERR, 
	AMS_CRM_STATE_OPERATE_REST_TIMEOUT_LEN_ERR,	
	AMS_CRM_STATE_OPERATE_REST_TIMEOUT_AMS_PID_ERR,
	AMS_CRM_STATE_OPERATE_REST_TIMEOUT_TELLER_ID_ERR,
	AMS_CRM_STATE_OPERATE_REST_TIMEOUT_SERVICE_GROUP_ID_ERR, 	
	AMS_CRM_STATE_OPERATE_REST_TIMEOUT_SERVICE_STATE_ERR, 	
	
	AMS_CRM_MODIFY_PASSWORD_PARA_ERR = (0x0400 + AMS_CRM_QUEUE_MNG_REASON_BASE),
	AMS_CRM_MODIFY_PASSWORD_STATE_ERR, 
	AMS_CRM_MODIFY_PASSWORD_LEN_ERR,
	AMS_CRM_MODIFY_PASSWORD_AMS_PID_ERR,
	AMS_CRM_MODIFY_PASSWORD_TELLER_ID_ERR,
	AMS_CRM_MODIFY_PASSWORD_OLD_PASSWORD_ERR,
	AMS_CRM_MODIFY_PASSWORD_NEW_PASSWORD_ERR,
	AMS_CRM_MODIFY_PASSWORD_SERVICE_GROUP_ID_ERR,
	AMS_CRM_MODIFY_PASSWORD_SERVICE_STATE_ERR,
	AMS_CRM_MODIFY_PASSWORD_TELLER_POS_ERR,

	AMS_CRM_FORCE_LOGIN_PARA_ERR = (0x1700 + AMS_CRM_QUEUE_MNG_REASON_BASE),
	AMS_CRM_FORCE_LOGIN_STATE_ERR,
	AMS_CRM_FORCE_LOGIN_LEN_ERR,
	AMS_CRM_FORCE_LOGIN_LP_RESOURCE_LIMITED,
	AMS_CRM_FORCE_LOGIN_NODE_RESOURCE_LIMITED,
	AMS_CRM_FORCE_LOGIN_TELLER_LEN_ERR,	
	AMS_CRM_FORCE_LOGIN_TELLER_NO_ERR,
	AMS_CRM_FORCE_LOGIN_TELLER_PWD_ERR,
	AMS_CRM_FORCE_LOGIN_TERM_NET_INFO_ERR,
	AMS_CRM_FORCE_LOGIN_TELLER_VNC_AUTH_PWD_ERR,	
	AMS_CRM_FORCE_LOGIN_TELLER_LOGIN_REPEATEDLY,
	AMS_CRM_FORCE_LOGIN_TELLER_TYPE_ERR,	
	AMS_CRM_FORCE_LOGIN_TELLER_NUM_ERR,
	AMS_CRM_FORCE_LOGIN_FILE_SERVER_USR_NAME_ERR,
	AMS_CRM_FORCE_LOGIN_FILE_SERVER_USR_PWD_ERR,
	AMS_CRM_FORCE_LOGIN_LICENSE_TIMEOUT, //LIC
	AMS_CRM_FORCE_LOGIN_TELLER_NUM_BEYOND_LIC, //LIC
	
	AMS_CRM_QUERY_INFO_PARA_ERR = (0x2f00 + AMS_CRM_QUEUE_MNG_REASON_BASE),
	AMS_CRM_QUERY_INFO_STATE_ERR, 
	AMS_CRM_QUERY_INFO_LEN_ERR,	
	AMS_CRM_QUERY_INFO_AMS_PID_ERR,
	AMS_CRM_QUERY_INFO_TELLER_ID_ERR,
	AMS_CRM_QUERY_INFO_SERVICE_GROUP_ID_ERR, 	
	AMS_CRM_QUERY_INFO_SERVICE_STATE_ERR, 	
	AMS_CRM_QUERY_INFO_CODE_ERR,
	AMS_CRM_QUERY_INFO_TARGET_SRV_ID_ERR,
	AMS_CRM_QUERY_INFO_TARGET_SRV_NAME_LEN_ERR,	
	AMS_CRM_QUERY_INFO_TARGET_SRV_LV_ERR,		
	AMS_CRM_QUERY_INFO_TARGET_TELLER_NO_LEN_ERR,
	AMS_CRM_QUERY_INFO_TARGET_TELLER_NO_ERR,	
	AMS_CRM_QUERY_INFO_TELLER_NO_KEY_LEN_ERR,	
	AMS_CRM_QUERY_INFO_TELLER_NAME_KEY_LEN_ERR,	

	AMS_CRM_STATE_OPERATE_IND_CNF_PARA_ERR = (0x3280 + AMS_CRM_QUEUE_MNG_REASON_BASE),
	AMS_CRM_STATE_OPERATE_IND_CNF_STATE_ERR, 
	AMS_CRM_STATE_OPERATE_IND_CNF_LEN_ERR,	
	AMS_CRM_STATE_OPERATE_IND_CNF_AMS_PID_ERR,
	AMS_CRM_STATE_OPERATE_IND_CNF_TELLER_ID_ERR,
	AMS_CRM_STATE_OPERATE_IND_CNF_SERVICE_GROUP_ID_ERR, 
	AMS_CRM_STATE_OPERATE_IND_CNF_SERVICE_STATE_ERR, 	
	AMS_CRM_STATE_OPERATE_IND_CNF_MANAGER_AMS_PID_ERR,		
	AMS_CRM_STATE_OPERATE_IND_CNF_MANAGER_TELLER_ID_ERR,	
	AMS_CRM_STATE_OPERATE_IND_CNF_MANAGER_SERVICE_GROUP_ID_ERR,
	AMS_CRM_STATE_OPERATE_IND_CNF_MANAGER_SERVICE_STATE_ERR,
	AMS_CRM_STATE_OPERATE_IND_CNF_CODE_ERR,
	
	AMS_CRM_EVENT_NOTICE_PARA_ERR = (0x3700 + AMS_CRM_QUEUE_MNG_REASON_BASE),
	AMS_CRM_EVENT_NOTICE_STATE_ERR,
	AMS_CRM_EVENT_NOTICE_LEN_ERR,
	AMS_CRM_EVENT_NOTICE_SERVICE_GROUP_ID_ERR, 
	AMS_CRM_EVENT_NOTICE_SERVICE_STATE_ERR,	
	AMS_CRM_EVENT_NOTICE_CALL_ID_ERR,  
	AMS_CRM_EVENT_NOTICE_CALL_STATE_ERR,
	AMS_CRM_EVENT_NOTICE_AMS_PID_ERR,
	AMS_CRM_EVENT_NOTICE_TELLER_ID_ERR,	
	AMS_CRM_EVENT_NOTICE_TERM_ID_ERR,
	AMS_CRM_EVENT_NOTICE_TYPE_ERR,	
	AMS_CRM_EVENT_NOTICE_LACK_FILE_INFO,    
	AMS_CRM_EVENT_NOTICE_FILE_PATH_LEN_ERR,	
	AMS_CRM_EVENT_NOTICE_FILE_NAME_LEN_ERR,	
	
	AMS_CRM_QUEUE_MNG_OTHER_FAIL = (0x3fff + AMS_CRM_QUEUE_MNG_REASON_BASE), //0x4fff

};


#endif
