/******************************************************************
*
* FILE NAME						                           VERSION
*	
*	amsenum.h                                              v1.0.0
*
* DESCRIPTION
*
*	AMS应用管理服务器的枚举定义文件
*
* COPYRIGHT
*	
*	Switch & Network Division, Eastern Communications Company Limited
*
* HISTORY                                                        
*																  
*     NAME       DATE              REMARKS		            TARGET
*    edward  	 2015-12-18        Created version 1.0.0    for VTC
******************************************************************/
#ifndef AMSENUM_H
#define AMSENUM_H


#define AMS_COMMON_REASON_BASE                            0X0000
#define AMS_VTA_QUEUE_MNG_REASON_BASE                     0X1000
#define AMS_VTM_MNG_REASON_BASE                           0X5000
#define AMS_CALL_REASON_BASE                              0X7000

#define AMS_VTA_REASON_BASE                               0X8000
#define AMS_VTM_REASON_BASE                               0Xa000 
#define AMS_CMS_REASON_BASE                               0Xb000 
#define AMS_RCAS_REASON_BASE                              0Xc000 
#define AMS_OMMS_REASON_BASE                              0Xd000 


#define AMS_SERVICE_RSVD_VALUE                            0XFFFFFFFF
#define AMS_TELLER_IDLE_TIME_ALLOWED                      10//30
#define AMS_TELLER_CALL_TRANSFER_TIMES_ALLOWED            3
#define AMS_TELLER_SERVICE_QUALITY_THRESHOLD              7000
#define AMS_TELLER_SERVICE_QUALITY_EXPECT_ADD             100
#define AMS_TELLER_FATIGUE_VALUE_THRESHOLD                85
#define AMS_TELLER_FATIGUE_VALUE_CONNECT_NUM_WEIGHTING    60
#define AMS_TELLER_FATIGUE_VALUE_WORK_TIME_WEIGHTING      40


enum amsMsgType_t
{
	AMS_MSG_TYPE_NULL = 0,
	AMS_VTA_MSG,
	AMS_VTM_MSG,
	AMS_CMS_MSG,
	AMS_RCAS_MSG,

	AMS_B_MSG,
	AMS_C_MSG,
	
	AMS_OTHER_MSG_TYPE,
};


enum amsResultType_t
{
	AMS_COMMON_RESULT = 0,

	AMS_VTA_LOGIN_RESULT,
	AMS_VTA_LOGOUT_RESULT,
	AMS_VTA_HANDSHAKE_RESULT,	
	AMS_VTA_STATE_OPERATE_RESULT,
	AMS_VTA_MODIFY_PASSWORD_RESULT,
	AMS_VTA_SERVICE_REG_RESULT,  
	AMS_VTA_TRANSFER_CALL_RESULT,
	AMS_VTA_VOLUME_CTRL_RESULT,
	AMS_VTA_AUDIO_RECORD_RESULT,
	AMS_VTA_SCREEN_RECORD_RESULT,
	AMS_VTA_REMOTE_COOPERATIVE_RESULT,
	AMS_VTA_SNAP_RESULT,
	
	AMS_VTA_SEND_MSG_RESULT,
	AMS_VTA_RECV_MSG_RESULT,
	AMS_VTA_SEND_FILE_RESULT,
	AMS_VTA_RECV_FILE_RESULT,

	AMS_VTA_MULTI_SESS_RESULT,

	AMS_VTA_FORCE_LOGIN_RESULT,	
	AMS_VTA_QUERY_INFO_RESULT,
	
	AMS_MANAGER_ADD_VTA_RESULT,
	AMS_MANAGER_DEL_VTA_RESULT,
	AMS_MANAGER_MODIFY_VTA_RESULT,
	AMS_MANAGER_QUERY_VTA_RESULT,
	AMS_MANAGER_FORCE_LOGOUT_VTA_RESULT,
	AMS_MANAGER_SET_VTA_STATE_RESULT,
	AMS_MANAGER_QUERY_VTA_STATE_RESULT,
	AMS_MANAGER_MODIFY_QUEUE_RULE_RESULT,
	AMS_MANAGER_FORCE_REL_CALL_RESULT,

	AMS_INSPECTOR_MONITOR_RESULT,
	
	AMS_VTA_BANDWIDTH_NOTICE_RESULT,
	AMS_VTA_EVENT_NOTICE_RESULT,
	AMS_VTA_PARA_CFG_RESULT,	
	
	AMS_VTM_LOGIN_RESULT,	
	AMS_VTM_LOGOUT_RESULT,
	AMS_VTM_HANDSHAKE_RESULT,

	AMS_VTM_SEND_MSG_RESULT,
	AMS_VTM_RECV_MSG_RESULT,
	AMS_VTM_SEND_FILE_RESULT,
	AMS_VTM_RECV_FILE_RESULT,

	AMS_VTM_FORCE_LOGIN_RESULT,
	AMS_VTM_QUERY_INFO_RESULT,

	AMS_VTM_BANDWIDTH_NOTICE_RESULT,	
	AMS_VTM_EVENT_NOTICE_RESULT,
	
	AMS_VTM_PARA_CFG_RESULT,	
	
	AMS_CMS_VTA_REG_RESULT,
	AMS_CMS_VTM_REG_RESULT,
	AMS_CMS_GET_VTA_RESULT,
	AMS_CMS_QUERY_TERM_NETINFO_RESULT,
	AMS_CMS_EVENT_NOTICE_RESULT,
	AMS_CMS_EVENT_IND_RESULT,

	AMS_RCAS_HANDSHAKE_RESULT,
	AMS_RCAS_LOADCAPC_NOTICE_RESULT,

	AMS_OTHER_RESULT_TYPE,
};


enum amsCommonResult
{
	AMS_SUCCESS = AMS_COMMON_REASON_BASE,
	AMS_PARA_ERR,
	AMS_STATE_ERR,
	AMS_ALLOC_MEM_FAILED,
	AMS_ALLOC_LP_FAILED,
	AMS_ALLOC_LT_FAILED,

	AMS_PARA_CFG_INF_CNF_TIMEOUT = 0x001f,
	
	AMS_OTHER_FAILED             = 0x00ff,
};

enum amsVtaQueueMngResult
{
	AMS_VTA_QUEUE_MNG_SUCCESS = 0,

	AMS_VTA_LOGIN_PARA_ERR = AMS_VTA_QUEUE_MNG_REASON_BASE,
	AMS_VTA_LOGIN_STATE_ERR,
	AMS_VTA_LOGIN_LEN_ERR,
	AMS_VTA_LOGIN_LP_RESOURCE_LIMITED,
	AMS_VTA_LOGIN_NODE_RESOURCE_LIMITED,
	AMS_VTA_LOGIN_TELLER_LEN_ERR,	
	AMS_VTA_LOGIN_TELLER_NO_ERR,
	AMS_VTA_LOGIN_TELLER_PWD_ERR,
	AMS_VTA_LOGIN_TELLER_VNC_AUTH_PWD_ERR,	
	AMS_VTA_LOGIN_TELLER_LOGIN_REPEATEDLY,
	AMS_VTA_LOGIN_TELLER_TYPE_ERR,	
	AMS_VTA_LOGIN_TELLER_NUM_ERR,
	AMS_VTA_LOGIN_FILE_SERVER_USR_NAME_ERR,
	AMS_VTA_LOGIN_FILE_SERVER_USR_PWD_ERR,
	AMS_VTA_LOGIN_ORG_ID_ERR,
	AMS_VTA_LOGIN_ORG_STATE_ERR,	
	AMS_VTA_LOGIN_LICENSE_TIMEOUT, //LIC
	AMS_VTA_LOGIN_TELLER_NUM_BEYOND_LIC, //LIC
	
	AMS_VTA_LOGOUT_PARA_ERR = (0x0100 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_VTA_LOGOUT_STATE_ERR, 
	AMS_VTA_LOGOUT_LEN_ERR,
	AMS_VTA_LOGOUT_AMS_PID_ERR,
	AMS_VTA_LOGOUT_TELLER_ID_ERR,
	AMS_VTA_LOGOUT_SERVICE_GROUP_ID_ERR, 
	AMS_VTA_LOGOUT_SERVICE_STATE_ERR, 
	
	AMS_VTA_HANDSHAKE_PARA_ERR = (0x0200 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_VTA_HANDSHAKE_STATE_ERR, 
	AMS_VTA_HANDSHAKE_LEN_ERR,
	AMS_VTA_HANDSHAKE_AMS_PID_ERR,
	AMS_VTA_HANDSHAKE_TELLER_ID_ERR,
	AMS_VTA_HANDSHAKE_SERVICE_GROUP_ID_ERR, 
	AMS_VTA_HANDSHAKE_SERVICE_STATE_ERR, 	
	AMS_VTA_HANDSHAKE_CLEAR_INACTIVTE_TELLER, 
	
	AMS_VTA_STATE_OPERATE_PARA_ERR = (0x0300 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_VTA_STATE_OPERATE_STATE_ERR, 
	AMS_VTA_STATE_OPERATE_LEN_ERR,	
	AMS_VTA_STATE_OPERATE_AMS_PID_ERR,
	AMS_VTA_STATE_OPERATE_TELLER_ID_ERR,
	AMS_VTA_STATE_OPERATE_SERVICE_GROUP_ID_ERR, 	
	AMS_VTA_STATE_OPERATE_SERVICE_STATE_ERR, 	
	AMS_VTA_STATE_OPERATE_CODE_ERR,
	AMS_VTA_STATE_OPERATE_STATE_OP_REASON_ERR,
	AMS_VTA_STATE_OPERATE_STATE_OP_TIMELEN_ERR,
	AMS_VTA_STATE_OPERATE_UPDATE_STATE_ERR, 	
	AMS_VTA_STATE_OPERATE_START_TIMER_ERR,
	AMS_VTA_STATE_OPERATE_REST_TIMEOUT,
	
	AMS_VTA_STATE_OPERATE_REST_TIMEOUT_PARA_ERR = (0x0340 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_VTA_STATE_OPERATE_REST_TIMEOUT_STATE_ERR, 
	AMS_VTA_STATE_OPERATE_REST_TIMEOUT_LEN_ERR,	
	AMS_VTA_STATE_OPERATE_REST_TIMEOUT_AMS_PID_ERR,
	AMS_VTA_STATE_OPERATE_REST_TIMEOUT_TELLER_ID_ERR,
	AMS_VTA_STATE_OPERATE_REST_TIMEOUT_SERVICE_GROUP_ID_ERR, 	
	AMS_VTA_STATE_OPERATE_REST_TIMEOUT_SERVICE_STATE_ERR, 	
	
	AMS_VTA_MODIFY_PASSWORD_PARA_ERR = (0x0400 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_VTA_MODIFY_PASSWORD_STATE_ERR, 
	AMS_VTA_MODIFY_PASSWORD_LEN_ERR,
	AMS_VTA_MODIFY_PASSWORD_AMS_PID_ERR,
	AMS_VTA_MODIFY_PASSWORD_TELLER_ID_ERR,
	AMS_VTA_MODIFY_PASSWORD_OLD_PASSWORD_ERR,
	AMS_VTA_MODIFY_PASSWORD_NEW_PASSWORD_ERR,
	AMS_VTA_MODIFY_PASSWORD_SERVICE_GROUP_ID_ERR,
	AMS_VTA_MODIFY_PASSWORD_SERVICE_STATE_ERR,
	AMS_VTA_MODIFY_PASSWORD_TELLER_POS_ERR,
	
	AMS_VTA_SERVICE_REG_PARA_ERR = (0x0500 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_VTA_SERVICE_REG_STATE_ERR, 
	AMS_VTA_SERVICE_REG_LEN_ERR,
	AMS_VTA_SERVICE_REG_AMS_PID_ERR,
	AMS_VTA_SERVICE_REG_TELLER_ID_ERR,
	AMS_VTA_SERVICE_REG_SERVICE_GROUP_ID_ERR,
	AMS_VTA_SERVICE_REG_SERVICE_STATE_ERR,
	AMS_VTA_SERVICE_REG_SERVICE_RSVD_ERR,
	AMS_VTA_SERVICE_REG_SERVICE_UNSUPPORT,
	AMS_VTA_SERVICE_REG_SERVICE_UNMATCH,
	AMS_VTA_SERVICE_REG_SERVICE_REG_REPEATEDLY,
	AMS_VTA_SERVICE_REG_TELLER_POS_ERR,

	AMS_VTA_TRANSFER_CALL_PARA_ERR = (0x0600 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_VTA_TRANSFER_CALL_STATE_ERR, 
	AMS_VTA_TRANSFER_CALL_LEN_ERR,
	AMS_VTA_TRANSFER_CALL_AMS_PID_ERR,
	AMS_VTA_TRANSFER_CALL_TELLER_ID_ERR,
	AMS_VTA_TRANSFER_CALL_SERVICE_GROUP_ID_ERR,
	AMS_VTA_TRANSFER_CALL_SERVICE_STATE_ERR,
	AMS_VTA_TRANSFER_CALL_TARGET_TYPE_ERR,
	AMS_VTA_TRANSFER_CALL_TARGET_GROUP_ERR,
	AMS_VTA_TRANSFER_CALL_TARGET_TELLER_ERR,
	AMS_VTA_TRANSFER_CALL_CALLID_ERR,
	AMS_VTA_TRANSFER_CALL_START_TIMER_ERR,
	AMS_VTA_TRANSFER_CALL_TIMEOUT,
	
	AMS_VTA_VOLUME_CTRL_PARA_ERR = (0x0700 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_VTA_VOLUME_CTRL_STATE_ERR, 
	AMS_VTA_VOLUME_CTRL_LEN_ERR,
	AMS_VTA_VOLUME_CTRL_AMS_PID_ERR,
	AMS_VTA_VOLUME_CTRL_TELLER_ID_ERR,
	AMS_VTA_VOLUME_CTRL_SERVICE_GROUP_ID_ERR,
	AMS_VTA_VOLUME_CTRL_SERVICE_STATE_ERR,
	AMS_VTA_VOLUME_CTRL_TYPE_ERR,
	AMS_VTA_VOLUME_CTRL_START_TIMER_ERR,
	AMS_VTM_VOLUME_VTM_MUTE_TIMEOUT,
	AMS_VTM_VOLUME_VTM_UNMUTE_TIMEOUT,
	
	AMS_VTA_VOLUME_CTRL_TIMEOUT_PARA_ERR = (0x0740 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_VTA_VOLUME_CTRL_TIMEOUT_STATE_ERR, 
	AMS_VTA_VOLUME_CTRL_TIMEOUT_LEN_ERR,
	AMS_VTA_VOLUME_CTRL_TIMEOUT_AMS_PID_ERR,
	AMS_VTA_VOLUME_CTRL_TIMEOUT_TELLER_ID_ERR,
	AMS_VTA_VOLUME_CTRL_TIMEOUT_TELLER_STATE_ERR,	
	AMS_VTA_VOLUME_CTRL_TIMEOUT_SERVICE_GROUP_ID_ERR,
	AMS_VTA_VOLUME_CTRL_TIMEOUT_SERVICE_STATE_ERR,
	AMS_VTA_VOLUME_CTRL_TIMEOUT_TYPE_ERR,

	AMS_VTM_VOLUME_CTRL_PARA_ERR = (0x0800 + AMS_VTA_QUEUE_MNG_REASON_BASE), 
	AMS_VTM_VOLUME_CTRL_STATE_ERR,
	AMS_VTM_VOLUME_CTRL_LEN_ERR,	
	AMS_VTM_VOLUME_CTRL_AMS_PID_ERR,
	AMS_VTM_VOLUME_CTRL_TELLER_ID_ERR,	
	AMS_VTM_VOLUME_CTRL_VTM_ID_ERR,
	AMS_VTM_VOLUME_CTRL_TYPE_ERR,

	AMS_VTM_VOLUME_CTRL_VTM_REPORT_FAIL,
	
	AMS_VTA_AUDIO_RECORD_PARA_ERR = (0x0900 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_VTA_AUDIO_RECORD_STATE_ERR,
	AMS_VTA_AUDIO_RECORD_LEN_ERR,
	AMS_VTA_AUDIO_RECORD_AMS_PID_ERR,
	AMS_VTA_AUDIO_RECORD_TELLER_ID_ERR,
	AMS_VTA_AUDIO_RECORD_SERVICE_GROUP_ID_ERR,
	AMS_VTA_AUDIO_RECORD_SERVICE_STATE_ERR,
	AMS_VTA_AUDIO_RECORD_CALL_ID_ERR,	
	AMS_VTA_AUDIO_RECORD_CALL_STATE_ERR,
	AMS_VTA_AUDIO_RECORD_TYPE_ERR,
	AMS_VTA_AUDIO_RECORD_REC_STATE_ERR, 	
	AMS_VTA_AUDIO_RECORD_FILE_TYPE_ERR,
	AMS_VTA_AUDIO_RECORD_FILE_NAME_ERR,
	AMS_VTA_AUDIO_RECORD_FILE_PATH_ERR,
	
	AMS_VTA_SCREEN_RECORD_PARA_ERR = (0x0a00 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_VTA_SCREEN_RECORD_STATE_ERR, 
	AMS_VTA_SCREEN_RECORD_LEN_ERR,
	AMS_VTA_SCREEN_RECORD_AMS_PID_ERR,
	AMS_VTA_SCREEN_RECORD_TELLER_ID_ERR,
	AMS_VTA_SCREEN_RECORD_SERVICE_GROUP_ID_ERR,
	AMS_VTA_SCREEN_RECORD_SERVICE_STATE_ERR,
	AMS_VTA_SCREEN_RECORD_CALL_ID_ERR,	
	AMS_VTA_SCREEN_RECORD_CALL_STATE_ERR,
	AMS_VTA_SCREEN_RECORD_TYPE_ERR,
	AMS_VTA_SCREEN_RECORD_FILE_TYPE_ERR,
	AMS_VTA_SCREEN_RECORD_FILE_NAME_ERR,
	AMS_VTA_SCREEN_RECORD_FILE_PATH_ERR,
	
	AMS_VTA_REMOTE_COOPERATIVE_PARA_ERR = (0x0b00 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_VTA_REMOTE_COOPERATIVE_STATE_ERR, 
	AMS_VTA_REMOTE_COOPERATIVE_LEN_ERR,
	AMS_VTA_REMOTE_COOPERATIVE_AMS_PID_ERR,
	AMS_VTA_REMOTE_COOPERATIVE_TELLER_ID_ERR,
	AMS_VTA_REMOTE_COOPERATIVE_SERVICE_GROUP_ID_ERR,
	AMS_VTA_REMOTE_COOPERATIVE_SERVICE_STATE_ERR,
	AMS_VTA_REMOTE_COOPERATIVE_CALL_ID_ERR,	
	AMS_VTA_REMOTE_COOPERATIVE_CALL_STATE_ERR,
	AMS_VTA_REMOTE_COOPERATIVE_OP_TYPE_ERR,
	AMS_VTA_REMOTE_COOPERATIVE_OP_STATE_ERR,	
	AMS_VTA_REMOTE_COOPERATIVE_VTM_ID_ERR,	
	AMS_VTA_REMOTE_COOPERATIVE_VTM_STATE_ERR,		
	AMS_VTA_REMOTE_COOPERATIVE_RCAS_TRANS_PROTO_PARA_ERR,
	AMS_VTA_REMOTE_COOPERATIVE_RFB_INIT_PARA_FOR_VTM_ERR,
	AMS_VTA_REMOTE_COOPERATIVE_RFB_INIT_PARA_FOR_VTA_ERR,
	AMS_VTA_REMOTE_COOPERATIVE_VTA_TRANS_PROTO_PARA_ERR,
	AMS_VTA_REMOTE_COOPERATIVE_START_TIMER_TO_VTM_ERR,	
	
	AMS_VTA_REMOTE_COOPERATIVE_TIMEOUT_PARA_ERR = (0x0b40 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_VTA_REMOTE_COOPERATIVE_TIMEOUT_STATE_ERR, 
	AMS_VTA_REMOTE_COOPERATIVE_TIMEOUT_LEN_ERR,
	AMS_VTA_REMOTE_COOPERATIVE_TIMEOUT_AMS_PID_ERR,
	AMS_VTA_REMOTE_COOPERATIVE_TIMEOUT_TELLER_ID_ERR,
	AMS_VTA_REMOTE_COOPERATIVE_TIMEOUT_TELLER_STATE_ERR,
	AMS_VTA_REMOTE_COOPERATIVE_TIMEOUT_SERVICE_GROUP_ID_ERR,
	AMS_VTA_REMOTE_COOPERATIVE_TIMEOUT_SERVICE_STATE_ERR,
	AMS_VTA_REMOTE_COOPERATIVE_TIMEOUT_VTM_ID_ERR,
	AMS_VTA_REMOTE_COOPERATIVE_TIMEOUT_VTM_STATE_ERR,	
	AMS_VTA_REMOTE_COOPERATIVE_TIMEOUT_CALL_ID_ERR,		
	AMS_VTA_REMOTE_COOPERATIVE_TIMEOUT_OP_TYPE_ERR,
	
	AMS_RCAS_START_DESKTOP_SHARE_PARA_ERR = (0x0c00 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_RCAS_START_DESKTOP_SHARE_STATE_ERR,
	AMS_RCAS_START_DESKTOP_SHARE_LEN_ERR,	
	AMS_RCAS_START_DESKTOP_SHARE_TELLER_ID_ERR,	
	AMS_RCAS_START_DESKTOP_SHARE_SERVICE_GROUP_ID_ERR,
	AMS_RCAS_START_DESKTOP_SHARE_SERVICE_STATE_ERR,	
	AMS_RCAS_START_DESKTOP_SHARE_CALL_ID_ERR,
	AMS_RCAS_START_DESKTOP_SHARE_VTM_ID_ERR,
	AMS_RCAS_START_DESKTOP_SHARE_VTM_STATE_ERR,	
	AMS_RCAS_START_DESKTOP_SHARE_VTM_TRANS_PROTO_PARA_ERR,
	AMS_RCAS_START_DESKTOP_SHARE_VTA_TRANS_PROTO_PARA_ERR,
	AMS_RCAS_START_DESKTOP_SHARE_PIXEL_FORMAT_PARA_ERR,
	AMS_RCAS_START_DESKTOP_SHARE_ENCODING_PARA_ERR,
	AMS_RCAS_START_DESKTOP_SHARE_TIMEOUT,
	
	AMS_RCAS_STOP_DESKTOP_SHARE_PARA_ERR = (0x0c40 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_RCAS_STOP_DESKTOP_SHARE_STATE_ERR,
	AMS_RCAS_STOP_DESKTOP_SHARE_LEN_ERR,	
	AMS_RCAS_STOP_DESKTOP_SHARE_TELLER_ID_ERR,	
	AMS_RCAS_STOP_DESKTOP_SHARE_SERVICE_GROUP_ID_ERR,
	AMS_RCAS_STOP_DESKTOP_SHARE_SERVICE_STATE_ERR,		
	AMS_RCAS_STOP_DESKTOP_SHARE_CALL_ID_ERR,
	AMS_RCAS_STOP_DESKTOP_SHARE_VTM_ID_ERR,
	AMS_RCAS_STOP_DESKTOP_SHARE_VTM_STATE_ERR,		
	AMS_RCAS_STOP_DESKTOP_SHARE_TIMEOUT,

	AMS_RCAS_START_DESKTOP_CTRL_PARA_ERR = (0x0c80 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_RCAS_START_DESKTOP_CTRL_STATE_ERR,
	AMS_RCAS_START_DESKTOP_CTRL_LEN_ERR,	
	AMS_RCAS_START_DESKTOP_CTRL_TELLER_ID_ERR,	
	AMS_RCAS_START_DESKTOP_CTRL_SERVICE_GROUP_ID_ERR,
	AMS_RCAS_START_DESKTOP_CTRL_SERVICE_STATE_ERR,		
	AMS_RCAS_START_DESKTOP_CTRL_CALL_ID_ERR,
	AMS_RCAS_START_DESKTOP_CTRL_VTM_ID_ERR,
	AMS_RCAS_START_DESKTOP_CTRL_VTM_STATE_ERR,	
	AMS_RCAS_START_DESKTOP_CTRL_TIMEOUT,

	AMS_RCAS_STOP_DESKTOP_CTRL_PARA_ERR = (0x0cc0 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_RCAS_STOP_DESKTOP_CTRL_STATE_ERR,
	AMS_RCAS_STOP_DESKTOP_CTRL_LEN_ERR,	
	AMS_RCAS_STOP_DESKTOP_CTRL_TELLER_ID_ERR,
	AMS_RCAS_STOP_DESKTOP_CTRL_SERVICE_GROUP_ID_ERR,
	AMS_RCAS_STOP_DESKTOP_CTRL_SERVICE_STATE_ERR,		
	AMS_RCAS_STOP_DESKTOP_CTRL_CALL_ID_ERR,
	AMS_RCAS_STOP_DESKTOP_CTRL_VTM_ID_ERR,
	AMS_RCAS_STOP_DESKTOP_CTRL_VTM_STATE_ERR,	
	AMS_RCAS_STOP_DESKTOP_CTRL_TIMEOUT,

	AMS_RCAS_HANDSHAKE_PARA_ERR = (0x0d00 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_RCAS_HANDSHAKE_STATE_ERR,
	AMS_RCAS_HANDSHAKE_LEN_ERR,
	AMS_RCAS_HANDSHAKE_RCAS_MID_ERR,
	AMS_RCAS_HANDSHAKE_NO_RCAS_CAP_PARA,
	AMS_RCAS_HANDSHAKE_RCAS_CAP_PARA_ERR,
	AMS_RCAS_HANDSHAKE_CLEAR_INACTIVTE_RCAS,
 
	AMS_VTA_LOGOUT_RCAS_REMOTE_COOP_ABORT = (0x0d40 + AMS_VTA_QUEUE_MNG_REASON_BASE), 
	AMS_VTA_LOGOUT_VTM_REMOTE_COOP_ABORT,	
	AMS_VTA_FORCE_LOGIN_RCAS_REMOTE_COOP_ABORT,
	AMS_VTA_FORCE_LOGIN_VTM_REMOTE_COOP_ABORT,	
	AMS_VTA_HANDSHAKE_TIMEOUT_RCAS_REMOTE_COOP_ABORT,
	AMS_VTA_HANDSHAKE_TIMEOUT_VTM_REMOTE_COOP_ABORT,
	
	AMS_VTM_LOGOUT_RCAS_REMOTE_COOP_ABORT,
	AMS_VTM_LOGOUT_VTA_REMOTE_COOP_ABORT,	
	AMS_VTM_FORCE_LOGIN_RCAS_REMOTE_COOP_ABORT,
	AMS_VTM_FORCE_LOGIN_VTA_REMOTE_COOP_ABORT,	
	AMS_VTM_HANDSHAKE_TIMEOUT_RCAS_REMOTE_COOP_ABORT,
	AMS_VTM_HANDSHAKE_TIMEOUT_VTA_REMOTE_COOP_ABORT,

	AMS_RCAS_HANDSHAKE_TIMEOUT_VTA_REMOTE_COOP_ABORT,
	AMS_RCAS_HANDSHAKE_TIMEOUT_VTM_REMOTE_COOP_ABORT,

	AMS_RCAS_LOADCAPC_NOTICE_PARA_ERR = (0x0f00 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_RCAS_LOADCAPC_NOTICE_STATE_ERR,
	AMS_RCAS_LOADCAPC_NOTICE_LEN_ERR,
	AMS_RCAS_LOADCAPC_NOTICE_RCAS_MID_ERR,
	AMS_RCAS_LOADCAPC_NOTICE_CPU_LOAD_LEVEL_ERR,
	AMS_RCAS_LOADCAPC_NOTICE_CPU_LOAD_ERR,
	
	AMS_RCAS_SCREEN_SHARE_EVENT_PARA_ERR = (0x1000 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_RCAS_SCREEN_SHARE_EVENT_STATE_ERR,
	AMS_RCAS_SCREEN_SHARE_EVENT_LEN_ERR,	
	AMS_RCAS_SCREEN_SHARE_EVENT_TELLER_ID_ERR,	
	AMS_RCAS_SCREEN_SHARE_EVENT_SERVICE_GROUP_ID_ERR,		
	AMS_RCAS_SCREEN_SHARE_EVENT_CALL_ID_ERR,
	AMS_RCAS_SCREEN_SHARE_EVENT_VTM_ID_ERR,	
	AMS_RCAS_SCREEN_SHARE_EVENT_VTM_STATE_ERR,		
	AMS_RCAS_SCREEN_SHARE_EVENT_TYPE_ERR,	
	
	AMS_RCAS_SCREEN_SHARE_EVENT_RCAS_REPORT_FAIL,

	AMS_VTM_REMOTE_COOPERATIVE_PARA_ERR = (0x1100 + AMS_VTA_QUEUE_MNG_REASON_BASE), 
	AMS_VTM_REMOTE_COOPERATIVE_STATE_ERR,
	AMS_VTM_REMOTE_COOPERATIVE_LEN_ERR,	
	AMS_VTM_REMOTE_COOPERATIVE_AMS_PID_ERR,
	AMS_VTM_REMOTE_COOPERATIVE_TELLER_ID_ERR,	
	AMS_VTM_REMOTE_COOPERATIVE_VTM_ID_ERR,
	AMS_VTM_REMOTE_COOPERATIVE_VTM_STATE_ERR,
	AMS_VTM_REMOTE_COOPERATIVE_OP_TYPE_ERR,
	AMS_VTM_REMOTE_COOPERATIVE_OP_STATE_ERR,	
	AMS_VTM_REMOTE_COOPERATIVE_RCAS_OP_STATE_ERR,	
	
	AMS_VTM_REMOTE_COOPERATIVE_TELLER_POS_ERR, 
	AMS_VTM_REMOTE_COOPERATIVE_TELLER_ID_NOT_MATCH,	
	AMS_VTM_REMOTE_COOPERATIVE_VTM_POS_ERR, 
	AMS_VTM_REMOTE_COOPERATIVE_VTM_ID_NOT_MATCH,
	AMS_VTM_REMOTE_COOPERATIVE_RCAS_TRANS_PROTO_PARA_ERR,
	AMS_VTM_REMOTE_COOPERATIVE_VTM_TRANS_PROTO_PARA_ERR,
	AMS_VTM_REMOTE_COOPERATIVE_VTM_SECURITIES_PARA_ERR,
	AMS_VTM_REMOTE_COOPERATIVE_VTM_VNC_AUTH_PARA_ERR,
	AMS_VTM_REMOTE_COOPERATIVE_VTA_SECURITIES_PARA_ERR,
	AMS_VTM_REMOTE_COOPERATIVE_VTA_VNC_AUTH_PARA_ERR,

	AMS_VTM_REMOTE_COOPERATIVE_SELECT_RCAS_MODULE_FAIL,
	AMS_VTM_REMOTE_COOPERATIVE_START_TIMER_TO_RCAS_ERR,
	AMS_VTM_REMOTE_COOPERATIVE_VTM_REPORT_FAIL,

	AMS_VTA_SNAP_PARA_ERR = (0x1200 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_VTA_SNAP_STATE_ERR, 
	AMS_VTA_SNAP_LEN_ERR,
	AMS_VTA_SNAP_AMS_PID_ERR,
	AMS_VTA_SNAP_TELLER_ID_ERR,
	AMS_VTA_SNAP_SERVICE_GROUP_ID_ERR,
	AMS_VTA_SNAP_SERVICE_STATE_ERR,
	AMS_VTA_SNAP_CALL_ID_ERR,
	AMS_VTA_SNAP_CALL_STATE_ERR,
	AMS_VTA_SNAP_VTM_ID_ERR,
	AMS_VTA_SNAP_VTM_STATE_ERR,	
	AMS_VTA_SNAP_TYPE_ERR,
	AMS_VTA_SNAP_FILE_TYPE_ERR,
	AMS_VTA_SNAP_FILE_NAME_ERR,
	AMS_VTA_SNAP_FILE_PATH_ERR,
	AMS_VTA_SNAP_START_TIMER_ERR,
	AMS_VTA_SNAP_TIMEOUT,
	
	AMS_VTA_SNAP_TIMEOUT_PARA_ERR = (0x1240 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_VTA_SNAP_TIMEOUT_STATE_ERR, 
	AMS_VTA_SNAP_TIMEOUT_LEN_ERR,
	AMS_VTA_SNAP_TIMEOUT_AMS_PID_ERR,
	AMS_VTA_SNAP_TIMEOUT_TELLER_ID_ERR,
	AMS_VTA_SNAP_TIMEOUT_TELLER_STATE_ERR,	
	AMS_VTA_SNAP_TIMEOUT_SERVICE_GROUP_ID_ERR,
	AMS_VTA_SNAP_TIMEOUT_SERVICE_STATE_ERR,
	AMS_VTA_SNAP_TIMEOUT_CALL_ID_ERR,	
	AMS_VTA_SNAP_TIMEOUT_TYPE_ERR,

	AMS_VTM_SNAP_PARA_ERR = (0x1300 + AMS_VTA_QUEUE_MNG_REASON_BASE), 
	AMS_VTM_SNAP_STATE_ERR,
	AMS_VTM_SNAP_LEN_ERR,	
	AMS_VTM_SNAP_AMS_PID_ERR,
	AMS_VTM_SNAP_TELLER_ID_ERR,	
	AMS_VTM_SNAP_VTM_ID_ERR,
	AMS_VTM_SNAP_TYPE_ERR,

	AMS_VTM_SNAP_VTM_REPORT_FAIL,

	AMS_VTA_SEND_MSG_PARA_ERR = (0x1400 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_VTA_SEND_MSG_STATE_ERR, 
	AMS_VTA_SEND_MSG_LEN_ERR,
	AMS_VTA_SEND_MSG_AMS_PID_ERR,
	AMS_VTA_SEND_MSG_TELLER_ID_ERR,
	AMS_VTA_SEND_MSG_SERVICE_GROUP_ID_ERR,
	AMS_VTA_SEND_MSG_SERVICE_STATE_ERR,
	AMS_VTA_SEND_MSG_TARGET_TYPE_ERR,
	AMS_VTA_SEND_MSG_TARGET_TELLER_ID_ERR,
	AMS_VTA_SEND_MSG_TARGET_TELLER_STATE_ERR,
	AMS_VTA_SEND_MSG_TARGET_TELLER_AMS_PID_ERR,	
	AMS_VTA_SEND_MSG_TARGET_VTM_ID_ERR,	
	AMS_VTA_SEND_MSG_TARGET_VTM_STATE_ERR,	
	AMS_VTA_SEND_MSG_MSG_LEN_ERR,
	AMS_VTA_SEND_MSG_MSG_SEND_STATE_ERR,
	AMS_VTA_SEND_MSG_START_TIMER_ERR,

	AMS_VTA_RECV_MSG_PARA_ERR = (0x1440 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_VTA_RECV_MSG_STATE_ERR, 
	AMS_VTA_RECV_MSG_LEN_ERR,
	AMS_VTA_RECV_MSG_AMS_PID_ERR,
	AMS_VTA_RECV_MSG_TELLER_ID_ERR,
	AMS_VTA_RECV_MSG_SERVICE_GROUP_ID_ERR,
	AMS_VTA_RECV_MSG_SERVICE_STATE_ERR,
	AMS_VTA_RECV_MSG_CALL_ID_ERR,
	AMS_VTA_RECV_MSG_ORIGIN_TYPE_ERR,
	AMS_VTA_RECV_MSG_ORIGIN_TELLER_ID_ERR,
	AMS_VTA_RECV_MSG_ORIGIN_TELLER_STATE_ERR,
	AMS_VTA_RECV_MSG_ORIGIN_TELLER_AMS_PID_ERR,
	AMS_VTA_RECV_MSG_ORIGIN_TELLER_SERVICE_GROUP_ID_ERR,
	AMS_VTA_RECV_MSG_ORIGIN_TELLER_SERVICE_STATE_ERR,
	AMS_VTA_RECV_MSG_ORIGIN_VTM_ID_ERR,	
	AMS_VTA_RECV_MSG_ORIGIN_VTM_STATE_ERR,	
	AMS_VTA_RECV_MSG_MSG_RECV_STATE_ERR,
	AMS_VTA_RECV_MSG_VTA_REPORT_FAIL,
	
	AMS_VTA_RECV_MSG_TIMEOUT_PARA_ERR = (0x1480 + AMS_VTM_MNG_REASON_BASE),                         
	AMS_VTA_RECV_MSG_TIMEOUT_LEN_ERR,                                                                                                                   
	AMS_VTA_RECV_MSG_TIMEOUT_SERVICE_GROUP_ID_ERR,                         
	AMS_VTA_RECV_MSG_TIMEOUT_SERVICE_STATE_ERR,                                                           
	AMS_VTA_RECV_MSG_TIMEOUT_ORIGIN_TYPE_ERR,
	AMS_VTA_RECV_MSG_TIMEOUT_ORIGIN_TELLER_ID_ERR,
	AMS_VTA_RECV_MSG_TIMEOUT_ORIGIN_TELLER_STATE_ERR,
	AMS_VTA_RECV_MSG_TIMEOUT_ORIGIN_TELLER_AMS_PID_ERR,	
	AMS_VTA_RECV_MSG_TIMEOUT_ORIGIN_VTM_ID_ERR,	
	AMS_VTA_RECV_MSG_TIMEOUT_ORIGIN_VTM_STATE_ERR,	    
		
	AMS_VTA_SEND_FILE_PARA_ERR = (0x1500 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_VTA_SEND_FILE_STATE_ERR, 
	AMS_VTA_SEND_FILE_LEN_ERR,
	AMS_VTA_SEND_FILE_AMS_PID_ERR,
	AMS_VTA_SEND_FILE_TELLER_ID_ERR,
	AMS_VTA_SEND_FILE_SERVICE_GROUP_ID_ERR,
	AMS_VTA_SEND_FILE_SERVICE_STATE_ERR,
	AMS_VTA_SEND_FILE_TARGET_TYPE_ERR,
	AMS_VTA_SEND_FILE_TARGET_TELLER_ID_ERR,
	AMS_VTA_SEND_FILE_TARGET_TELLER_STATE_ERR,
	AMS_VTA_SEND_FILE_TARGET_TELLER_AMS_PID_ERR,
	AMS_VTA_SEND_FILE_TARGET_VTM_ID_ERR,
	AMS_VTA_SEND_FILE_TARGET_VTM_STATE_ERR,		
	AMS_VTA_SEND_FILE_OP_TYPE_ERR,
	AMS_VTA_SEND_FILE_FILE_TYPE_ERR,
	AMS_VTA_SEND_FILE_FILE_PATH_ERR,	
	AMS_VTA_SEND_FILE_FILE_NAME_ERR,
	AMS_VTA_SEND_FILE_START_TIMER_ERR,

	AMS_VTA_SEND_FILE_FILE_SEND_STATE_ERR,

	AMS_VTA_RECV_FILE_PARA_ERR = (0x1540 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_VTA_RECV_FILE_STATE_ERR, 
	AMS_VTA_RECV_FILE_LEN_ERR,
	AMS_VTA_RECV_FILE_AMS_PID_ERR,
	AMS_VTA_RECV_FILE_TELLER_ID_ERR,
	AMS_VTA_RECV_FILE_SERVICE_GROUP_ID_ERR,
	AMS_VTA_RECV_FILE_SERVICE_STATE_ERR,
	AMS_VTA_RECV_FILE_CALL_ID_ERR,
	AMS_VTA_RECV_FILE_ORIGIN_TYPE_ERR,
	AMS_VTA_RECV_FILE_ORIGIN_TELLER_ID_ERR,
	AMS_VTA_RECV_FILE_ORIGIN_TELLER_STATE_ERR,
	AMS_VTA_RECV_FILE_ORIGIN_TELLER_AMS_PID_ERR,
	AMS_VTA_RECV_FILE_ORIGIN_TELLER_SERVICE_GROUP_ID_ERR,
	AMS_VTA_RECV_FILE_ORIGIN_TELLER_SERVICE_STATE_ERR,
	AMS_VTA_RECV_FILE_ORIGIN_VTM_ID_ERR,	
	AMS_VTA_RECV_FILE_ORIGIN_VTM_STATE_ERR,		
	AMS_VTA_RECV_FILE_FILE_RECV_OP_TYPE_ERR,
	AMS_VTA_RECV_FILE_FILE_SERVICE_TYPE_ERR,
	AMS_VTA_RECV_FILE_FILE_RECV_STATE_ERR,
	AMS_VTA_RECV_SNAP_FILE_STATE_ERR,
	
	AMS_VTA_RECV_FILE_VTA_REPORT_FAIL,
	AMS_VTA_RECV_SNAP_FILE_VTA_REPORT_FAIL,
	AMS_VTA_RECV_FILE_TIMEOUT,
	
	AMS_VTA_RECV_FILE_TIMEOUT_PARA_ERR = (0x1580 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_VTA_RECV_FILE_TIMEOUT_LEN_ERR,
	AMS_VTA_RECV_FILE_TIMEOUT_SERVICE_GROUP_ID_ERR,
	AMS_VTA_RECV_FILE_TIMEOUT_SERVICE_STATE_ERR,
	AMS_VTA_RECV_FILE_TIMEOUT_FILE_RECV_OP_TYPE_ERR,
	AMS_VTA_RECV_FILE_TIMEOUT_FILE_SERVICE_TYPE_ERR,
	AMS_VTA_RECV_FILE_TIMEOUT_ORIGIN_TYPE_ERR,
	AMS_VTA_RECV_FILE_TIMEOUT_ORIGIN_TELLER_ID_ERR,
	AMS_VTA_RECV_FILE_TIMEOUT_ORIGIN_TELLER_STATE_ERR,
	AMS_VTA_RECV_FILE_TIMEOUT_ORIGIN_TELLER_AMS_PID_ERR,
	AMS_VTA_RECV_FILE_TIMEOUT_ORIGIN_VTM_ID_ERR,
	AMS_VTA_RECV_FILE_TIMEOUT_ORIGIN_VTM_STATE_ERR,

	AMS_VTA_MULTI_SESS_PARA_ERR = (0x1600 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_VTA_MULTI_SESS_STATE_ERR, 
	AMS_VTA_MULTI_SESS_LEN_ERR,
	AMS_VTA_MULTI_SESS_AMS_PID_ERR,
	AMS_VTA_MULTI_SESS_TELLER_ID_ERR,
	AMS_VTA_MULTI_SESS_SERVICE_GROUP_ID_ERR,
	AMS_VTA_MULTI_SESS_SERVICE_STATE_ERR,
	AMS_VTA_MULTI_SESS_CALL_ID_ERR,
	AMS_VTA_MULTI_SESS_CALL_STATE_ERR,
	AMS_VTA_MULTI_SESS_VTM_ID_ERR,
	AMS_VTA_MULTI_SESS_VTM_STATE_ERR,	
	AMS_VTA_MULTI_SESS_TARGET_TYPE_ERR,
	AMS_VTA_MULTI_SESS_TARGET_TELLER_ID_ERR,
	AMS_VTA_MULTI_SESS_TARGET_TELLER_STATE_ERR,
	AMS_VTA_MULTI_SESS_TARGET_TELLER_AMS_PID_ERR,
	AMS_VTA_MULTI_SESS_OP_TYPE_ERR,
	AMS_VTA_MULTI_SESS_OP_STATE_ERR,
	AMS_VTA_MULTI_SESS_START_TIMER_ERR,
	AMS_VTA_MULTI_SESS_TIMEOUT,
	
	AMS_VTA_MULTI_SESS_TIMEOUT_PARA_ERR = (0x1640 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_VTA_MULTI_SESS_TIMEOUT_LEN_ERR,
	AMS_VTA_MULTI_SESS_TIMEOUT_TELLER_ID_ERR,
	AMS_VTA_MULTI_SESS_TIMEOUT_TELLER_STATE_ERR,	
	AMS_VTA_MULTI_SESS_TIMEOUT_SERVICE_GROUP_ID_ERR,
	AMS_VTA_MULTI_SESS_TIMEOUT_SERVICE_STATE_ERR,
	AMS_VTA_MULTI_SESS_TIMEOUT_OP_TYPE_ERR,
	AMS_VTA_MULTI_SESS_TIMEOUT_TARGET_TYPE_ERR,
	AMS_VTA_MULTI_SESS_TIMEOUT_TARGET_TELLER_ID_ERR,
	AMS_VTA_MULTI_SESS_TIMEOUT_TARGET_TELLER_STATE_ERR,
	AMS_VTA_MULTI_SESS_TIMEOUT_TARGET_TELLER_AMS_PID_ERR,
	AMS_VTA_MULTI_SESS_TIMEOUT_TARGET_VTM_ID_ERR,
	AMS_VTA_MULTI_SESS_TIMEOUT_TARGET_VTM_STATE_ERR,
	
	AMS_VTA_MULTI_SESS_IND_CNF_PARA_ERR = (0x1680 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_VTA_MULTI_SESS_IND_CNF_STATE_ERR, 
	AMS_VTA_MULTI_SESS_IND_CNF_LEN_ERR,
	AMS_VTA_MULTI_SESS_IND_CNF_AMS_PID_ERR,
	AMS_VTA_MULTI_SESS_IND_CNF_TELLER_ID_ERR,
	AMS_VTA_MULTI_SESS_IND_CNF_SERVICE_GROUP_ID_ERR,
	AMS_VTA_MULTI_SESS_IND_CNF_SERVICE_STATE_ERR,
	AMS_VTA_MULTI_SESS_IND_CNF_CALL_ID_ERR,
	AMS_VTA_MULTI_SESS_IND_CNF_CALL_STATE_ERR,
	AMS_VTA_MULTI_SESS_IND_CNF_ORIGIN_TYPE_ERR,
	AMS_VTA_MULTI_SESS_IND_CNF_ORIGIN_TELLER_ID_ERR,
	AMS_VTA_MULTI_SESS_IND_CNF_ORIGIN_TELLER_STATE_ERR,
	AMS_VTA_MULTI_SESS_IND_CNF_ORIGIN_TELLER_AMS_PID_ERR,
	AMS_VTA_MULTI_SESS_IND_CNF_ORIGIN_TELLER_SERVICE_GROUP_ID_ERR,
	AMS_VTA_MULTI_SESS_IND_CNF_ORIGIN_TELLER_SERVICE_STATE_ERR,
	AMS_VTA_MULTI_SESS_IND_CNF_ORIGIN_VTM_ID_ERR,	
	AMS_VTA_MULTI_SESS_IND_CNF_ORIGIN_VTM_STATE_ERR,		
	AMS_VTA_MULTI_SESS_IND_CNF_OP_TYPE_ERR,
	AMS_VTA_MULTI_SESS_IND_CNF_OP_STATE_ERR,

	AMS_VTA_MULTI_SESS_IND_CNF_VTA_REPORT_FAIL,

	AMS_VTA_FORCE_LOGIN_PARA_ERR = (0x1700 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_VTA_FORCE_LOGIN_STATE_ERR,
	AMS_VTA_FORCE_LOGIN_LEN_ERR,
	AMS_VTA_FORCE_LOGIN_LP_RESOURCE_LIMITED,
	AMS_VTA_FORCE_LOGIN_NODE_RESOURCE_LIMITED,
	AMS_VTA_FORCE_LOGIN_TELLER_LEN_ERR,	
	AMS_VTA_FORCE_LOGIN_TELLER_NO_ERR,
	AMS_VTA_FORCE_LOGIN_TELLER_PWD_ERR,
	AMS_VTA_FORCE_LOGIN_TERM_NET_INFO_ERR,
	AMS_VTA_FORCE_LOGIN_TELLER_VNC_AUTH_PWD_ERR,	
	AMS_VTA_FORCE_LOGIN_TELLER_LOGIN_REPEATEDLY,
	AMS_VTA_FORCE_LOGIN_TELLER_TYPE_ERR,	
	AMS_VTA_FORCE_LOGIN_TELLER_NUM_ERR,
	AMS_VTA_FORCE_LOGIN_FILE_SERVER_USR_NAME_ERR,
	AMS_VTA_FORCE_LOGIN_FILE_SERVER_USR_PWD_ERR,
	AMS_VTA_FORCE_LOGIN_LICENSE_TIMEOUT, //LIC
	AMS_VTA_FORCE_LOGIN_TELLER_NUM_BEYOND_LIC, //LIC
	
	AMS_VTA_QUERY_INFO_PARA_ERR = (0x2f00 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_VTA_QUERY_INFO_STATE_ERR, 
	AMS_VTA_QUERY_INFO_LEN_ERR,	
	AMS_VTA_QUERY_INFO_AMS_PID_ERR,
	AMS_VTA_QUERY_INFO_TELLER_ID_ERR,
	AMS_VTA_QUERY_INFO_SERVICE_GROUP_ID_ERR, 	
	AMS_VTA_QUERY_INFO_SERVICE_STATE_ERR, 	
	AMS_VTA_QUERY_INFO_CODE_ERR,
	AMS_VTA_QUERY_INFO_TARGET_SRV_ID_ERR,
	AMS_VTA_QUERY_INFO_TARGET_SRV_NAME_LEN_ERR,	
	AMS_VTA_QUERY_INFO_TARGET_SRV_LV_ERR,		
	AMS_VTA_QUERY_INFO_TARGET_TELLER_NO_LEN_ERR,
	AMS_VTA_QUERY_INFO_TARGET_TELLER_NO_ERR,	
	AMS_VTA_QUERY_INFO_TELLER_NO_KEY_LEN_ERR,	
	AMS_VTA_QUERY_INFO_TELLER_NAME_KEY_LEN_ERR,	
	
	AMS_MANAGER_ADD_VTA_PARA_ERR = (0x3000 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_MANAGER_ADD_VTA_STATE_ERR, 
	AMS_MANAGER_ADD_VTA_SERVICE_GROUP_ID_ERR,
	AMS_MANAGER_ADD_VTA_SERVICE_STATE_ERR,	
	AMS_MANAGER_ADD_VTA_LEN_ERR,
	AMS_MANAGER_ADD_VTA_AMS_PID_ERR,
	AMS_MANAGER_ADD_VTA_TELLER_ID_ERR,
	AMS_MANAGER_ADD_VTA_ADD_TELLER_ID_ERR,
	AMS_MANAGER_ADD_VTA_ADD_TELLER_NO_ERR,
	AMS_MANAGER_ADD_VTA_ADD_TELLER_PWD_ERR,
	AMS_MANAGER_ADD_VTA_ADD_TELLER_TYPE_ERR,
	AMS_MANAGER_ADD_VTA_RESOURCE_LIMITED,
	AMS_MANAGER_ADD_VTA_TELLER_NUM_ERR,

	AMS_MANAGER_DEL_VTA_PARA_ERR = (0x3040 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_MANAGER_DEL_VTA_STATE_ERR, 
	AMS_MANAGER_DEL_VTA_SERVICE_GROUP_ID_ERR, 
	AMS_MANAGER_DEL_VTA_SERVICE_STATE_ERR, 
	AMS_MANAGER_DEL_VTA_LEN_ERR,
	AMS_MANAGER_DEL_VTA_AMS_PID_ERR,
	AMS_MANAGER_DEL_VTA_TELLER_ID_ERR,
	AMS_MANAGER_DEL_VTA_DEL_TELLER_ID_ERR,
	AMS_MANAGER_DEL_VTA_DEL_TELLER_STATE_ERR,
	AMS_MANAGER_DEL_VTA_DEL_TELLER_UPDATE_STATE_ERR, 
	
	AMS_MANAGER_MODIFY_VTA_PARA_ERR = (0x3080 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_MANAGER_MODIFY_VTA_STATE_ERR, 
	AMS_MANAGER_MODIFY_VTA_SERVICE_GROUP_ID_ERR,
	AMS_MANAGER_MODIFY_VTA_SERVICE_STATE_ERR,	
	AMS_MANAGER_MODIFY_VTA_LEN_ERR,
	AMS_MANAGER_MODIFY_VTA_AMS_PID_ERR,
	AMS_MANAGER_MODIFY_VTA_TELLER_ID_ERR,
	AMS_MANAGER_MODIFY_VTA_MODIFY_TELLER_ID_ERR,
	AMS_MANAGER_MODIFY_VTA_MODIFY_TELLER_NO_ERR,
	AMS_MANAGER_MODIFY_VTA_MODIFY_TELLER_PWD_ERR,
	AMS_MANAGER_MODIFY_VTA_MODIFY_TELLER_TYPE_ERR,
	AMS_MANAGER_MODIFY_VTA_MODIFY_TELLER_STATE_ERR,

	AMS_MANAGER_QUERY_VTA_PARA_ERR = (0x30c0 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_MANAGER_QUERY_VTA_STATE_ERR, 
	AMS_MANAGER_QUERY_VTA_SERVICE_GROUP_ID_ERR,
	AMS_MANAGER_QUERY_VTA_SERVICE_STATE_ERR,	
	AMS_MANAGER_QUERY_VTA_LEN_ERR,
	AMS_MANAGER_QUERY_VTA_AMS_PID_ERR,
	AMS_MANAGER_QUERY_VTA_TELLER_ID_ERR,
	AMS_MANAGER_QUERY_VTA_QUERY_TELLER_ID_ERR,
	AMS_MANAGER_QUERY_VTA_QUERY_TELLER_NAME_ERR,
	AMS_MANAGER_QUERY_VTA_QUERY_TELLER_PWD_ERR,
	AMS_MANAGER_QUERY_VTA_QUERY_TELLER_TYPE_ERR,

	AMS_MANAGER_FORCE_LOGOUT_VTA_PARA_ERR = (0x3100 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_MANAGER_FORCE_LOGOUT_VTA_STATE_ERR, 
	AMS_MANAGER_FORCE_LOGOUT_VTA_SERVICE_GROUP_ID_ERR,
	AMS_MANAGER_FORCE_LOGOUT_VTA_SERVICE_STATE_ERR,	
	AMS_MANAGER_FORCE_LOGOUT_VTA_LEN_ERR,
	AMS_MANAGER_FORCE_LOGOUT_VTA_AMS_PID_ERR,
	AMS_MANAGER_FORCE_LOGOUT_VTA_TELLER_ID_ERR,
	AMS_MANAGER_FORCE_LOGOUT_VTA_TELLER_TYPE_ERR,	
	AMS_MANAGER_FORCE_LOGOUT_VTA_TARGET_TELLER_ID_ERR,
	AMS_MANAGER_FORCE_LOGOUT_VTA_TARGET_TELLER_STATE_ERR,
	AMS_MANAGER_FORCE_LOGOUT_VTA_TARGET_TELLER_SERVICE_GROUP_ID_ERR,
	AMS_MANAGER_FORCE_LOGOUT_VTA_UPDATE_STATE_ERR,

	AMS_MANAGER_SET_VTA_STATE_PARA_ERR = (0x3200 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_MANAGER_SET_VTA_STATE_STATE_ERR, 
	AMS_MANAGER_SET_VTA_STATE_LEN_ERR,
	AMS_MANAGER_SET_VTA_STATE_AMS_PID_ERR,
	AMS_MANAGER_SET_VTA_STATE_TELLER_ID_ERR,
	AMS_MANAGER_SET_VTA_STATE_TELLER_TYPE_ERR,	
	AMS_MANAGER_SET_VTA_STATE_SERVICE_GROUP_ID_ERR,
	AMS_MANAGER_SET_VTA_STATE_SERVICE_STATE_ERR,
	AMS_MANAGER_SET_VTA_STATE_ST_SET_STATE_ERR, 
	AMS_MANAGER_SET_VTA_STATE_START_TIMER_ERR,
	AMS_MANAGER_SET_VTA_STATE_SET_TELLER_AMS_PID_ERR,
	AMS_MANAGER_SET_VTA_STATE_SET_TELLER_ID_ERR,
	AMS_MANAGER_SET_VTA_STATE_SET_TELLER_SERVICE_GROUP_ID_ERR,
	AMS_MANAGER_SET_VTA_STATE_SET_TELLER_SERVICE_STATE_ERR,
	AMS_MANAGER_SET_VTA_STATE_SET_TELLER_STATE_ERR, 
	AMS_MANAGER_SET_VTA_STATE_GET_OPERATE_IND_ERR,
	AMS_MANAGER_SET_VTA_STATE_GET_STATE_ERR,
	AMS_MANAGER_SET_VTA_STATE_UPDATE_STATE_ERR,
	AMS_MANAGER_SET_VTA_STATE_VTA_REPORT_FAIL,
	AMS_MANAGER_SET_VTA_STATE_VTA_TIMEOUT, 
	
	AMS_MANAGER_SET_VTA_STATE_TIMEOUT_PARA_ERR = (0x3240 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_MANAGER_SET_VTA_STATE_TIMEOUT_STATE_ERR, 
	AMS_MANAGER_SET_VTA_STATE_TIMEOUT_LEN_ERR,
	AMS_MANAGER_SET_VTA_STATE_TIMEOUT_AMS_PID_ERR,
	AMS_MANAGER_SET_VTA_STATE_TIMEOUT_TELLER_ID_ERR,
	AMS_MANAGER_SET_VTA_STATE_TIMEOUT_SERVICE_GROUP_ID_ERR,
	AMS_MANAGER_SET_VTA_STATE_TIMEOUT_SERVICE_STATE_ERR,
	AMS_MANAGER_SET_VTA_STATE_TIMEOUT_ST_SET_STATE_ERR,

	AMS_VTA_STATE_OPERATE_IND_CNF_PARA_ERR = (0x3280 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_VTA_STATE_OPERATE_IND_CNF_STATE_ERR, 
	AMS_VTA_STATE_OPERATE_IND_CNF_LEN_ERR,	
	AMS_VTA_STATE_OPERATE_IND_CNF_AMS_PID_ERR,
	AMS_VTA_STATE_OPERATE_IND_CNF_TELLER_ID_ERR,
	AMS_VTA_STATE_OPERATE_IND_CNF_SERVICE_GROUP_ID_ERR, 
	AMS_VTA_STATE_OPERATE_IND_CNF_SERVICE_STATE_ERR, 	
	AMS_VTA_STATE_OPERATE_IND_CNF_MANAGER_AMS_PID_ERR,		
	AMS_VTA_STATE_OPERATE_IND_CNF_MANAGER_TELLER_ID_ERR,	
	AMS_VTA_STATE_OPERATE_IND_CNF_MANAGER_SERVICE_GROUP_ID_ERR,
	AMS_VTA_STATE_OPERATE_IND_CNF_MANAGER_SERVICE_STATE_ERR,
	AMS_VTA_STATE_OPERATE_IND_CNF_CODE_ERR,
	
	AMS_MANAGER_QUERY_VTA_STATE_PARA_ERR = (0x3300 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_MANAGER_QUERY_VTA_STATE_STATE_ERR, 
	AMS_MANAGER_QUERY_VTA_STATE_LEN_ERR,
	AMS_MANAGER_QUERY_VTA_STATE_AMS_PID_ERR,
	AMS_MANAGER_QUERY_VTA_STATE_TELLER_ID_ERR,
	AMS_MANAGER_QUERY_VTA_STATE_TELLER_TYPE_ERR,	
	AMS_MANAGER_QUERY_VTA_STATE_SERVICE_GROUP_ID_ERR,
	AMS_MANAGER_QUERY_VTA_STATE_SERVICE_STATE_ERR,		
	AMS_MANAGER_QUERY_VTA_STATE_START_TIMER_ERR,
	AMS_MANAGER_QUERY_VTA_STATE_QUERY_TELLER_AMS_PID_ERR,
	AMS_MANAGER_QUERY_VTA_STATE_QUERY_TELLER_ID_ERR,
	AMS_MANAGER_QUERY_VTA_STATE_QUERY_TELLER_SERVICE_GROUP_ID_ERR,
	AMS_MANAGER_QUERY_VTA_STATE_QUERY_TELLER_SERVICE_STATE_ERR,
	AMS_MANAGER_QUERY_VTA_STATE_QUERY_TELLER_STATE_ERR, 
	
	AMS_MANAGER_MODIFY_QUEUE_RULE_PARA_ERR = (0x3340 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_MANAGER_MODIFY_QUEUE_RULE_STATE_ERR, 
	AMS_MANAGER_MODIFY_QUEUE_RULE_LEN_ERR,
	AMS_MANAGER_MODIFY_QUEUE_RULE_AMS_PID_ERR,
	AMS_MANAGER_MODIFY_QUEUE_RULE_TELLER_ID_ERR,
	AMS_MANAGER_MODIFY_QUEUE_RULE_SERVICE_GROUP_ID_ERR,
	AMS_MANAGER_MODIFY_QUEUE_RULE_SERVICE_STATE_ERR,		
	AMS_MANAGER_MODIFY_QUEUE_RULE_START_TIMER_ERR,
	AMS_MANAGER_MODIFY_QUEUE_RULE_MODIFY_VTM_AMS_PID_ERR,
	AMS_MANAGER_MODIFY_QUEUE_RULE_MODIFY_VTM_ID_ERR,
	AMS_MANAGER_MODIFY_QUEUE_RULE_MODIFY_VTM_SERVICE_GROUP_ID_ERR,
	AMS_MANAGER_MODIFY_QUEUE_RULE_MODIFY_VTM_SERVICE_STATE_ERR,
	AMS_MANAGER_MODIFY_QUEUE_RULE_MODIFY_VTM_STATE_ERR, 
	AMS_MANAGER_MODIFY_QUEUE_RULE_MODIFY_VTM_SEQUENCE_ERR, 
	AMS_MANAGER_MODIFY_QUEUE_RULE_TIMEOUT,

	AMS_MANAGER_FORCE_REL_CALL_PARA_ERR = (0x3400 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_MANAGER_FORCE_REL_CALL_STATE_ERR, 
	AMS_MANAGER_FORCE_REL_CALL_LEN_ERR,
	AMS_MANAGER_FORCE_REL_CALL_AMS_PID_ERR,
	AMS_MANAGER_FORCE_REL_CALL_TELLER_ID_ERR,
	AMS_MANAGER_FORCE_REL_CALL_TELLER_TYPE_ERR,	
	AMS_MANAGER_FORCE_REL_CALL_SERVICE_GROUP_ID_ERR,
	AMS_MANAGER_FORCE_REL_CALL_SERVICE_STATE_ERR,	
	AMS_MANAGER_FORCE_REL_CALL_TARGET_TELLER_ID_ERR,
	AMS_MANAGER_FORCE_REL_CALL_TARGET_TELLER_STATE_ERR,
	AMS_MANAGER_FORCE_REL_CALL_TARGET_TELLER_AMS_PID_ERR,
	AMS_MANAGER_FORCE_REL_CALL_TARGET_TELLER_SERVICE_GROUP_ID_ERR,
	AMS_MANAGER_FORCE_REL_CALL_TARGET_TELLER_SERVICE_STATE_ERR,		
	AMS_MANAGER_FORCE_REL_CALL_START_TIMER_ERR,
	
	AMS_INSPECTOR_MONITOR_PARA_ERR = (0x3500 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_INSPECTOR_MONITOR_STATE_ERR, 
	AMS_INSPECTOR_MONITOR_LEN_ERR,
	AMS_INSPECTOR_MONITOR_AMS_PID_ERR,
	AMS_INSPECTOR_MONITOR_TELLER_ID_ERR,
	AMS_INSPECTOR_MONITOR_TELLER_TYPE_ERR,	
	AMS_INSPECTOR_MONITOR_SERVICE_GROUP_ID_ERR,
	AMS_INSPECTOR_MONITOR_SERVICE_STATE_ERR,		
	AMS_INSPECTOR_MONITOR_TARGET_TYPE_ERR,
	AMS_INSPECTOR_MONITOR_TARGET_TELLER_ID_ERR,
	AMS_INSPECTOR_MONITOR_TARGET_TELLER_STATE_ERR,
	AMS_INSPECTOR_MONITOR_TARGET_TELLER_AMS_PID_ERR,
	AMS_INSPECTOR_MONITOR_TARGET_TELLER_SERVICE_GROUP_ID_ERR,
	AMS_INSPECTOR_MONITOR_TARGET_TELLER_SERVICE_STATE_ERR,	
	AMS_INSPECTOR_MONITOR_TARGET_VTM_ID_ERR,
	AMS_INSPECTOR_MONITOR_TARGET_VTM_STATE_ERR,		
	AMS_INSPECTOR_MONITOR_OP_TYPE_ERR,
	AMS_INSPECTOR_MONITOR_OP_STATE_ERR,
	AMS_INSPECTOR_MONITOR_START_TIMER_ERR,

	AMS_INSPECTOR_MONITOR_VTA_REPORT_MONITOR_FAIL,
	AMS_INSPECTOR_MONITOR_VTA_REPORT_FORCE_INSERT_CALL_FAIL,
	AMS_INSPECTOR_MONITOR_TIMEOUT,
	
	AMS_INSPECTOR_MONITOR_TIMEOUT_PARA_ERR = (0x3540 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_INSPECTOR_MONITOR_TIMEOUT_LEN_ERR,
	AMS_INSPECTOR_MONITOR_TIMEOUT_TELLER_ID_ERR,
	AMS_INSPECTOR_MONITOR_TIMEOUT_TELLER_STATE_ERR,	
	AMS_INSPECTOR_MONITOR_TIMEOUT_SERVICE_GROUP_ID_ERR,
	AMS_INSPECTOR_MONITOR_TIMEOUT_SERVICE_STATE_ERR,
	AMS_INSPECTOR_MONITOR_TIMEOUT_OP_TYPE_ERR,	
	AMS_INSPECTOR_MONITOR_TIMEOUT_TARGET_TYPE_ERR,
	AMS_INSPECTOR_MONITOR_TIMEOUT_TARGET_TELLER_ID_ERR,
	AMS_INSPECTOR_MONITOR_TIMEOUT_TARGET_TELLER_STATE_ERR,
	AMS_INSPECTOR_MONITOR_TIMEOUT_TARGET_TELLER_AMS_PID_ERR,
	
	AMS_INSPECTOR_MONITOR_IND_CNF_PARA_ERR = (0x3580 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_INSPECTOR_MONITOR_IND_CNF_STATE_ERR, 
	AMS_INSPECTOR_MONITOR_IND_CNF_LEN_ERR,
	AMS_INSPECTOR_MONITOR_IND_CNF_AMS_PID_ERR,
	AMS_INSPECTOR_MONITOR_IND_CNF_TELLER_ID_ERR,
	AMS_INSPECTOR_MONITOR_IND_CNF_SERVICE_GROUP_ID_ERR,
	AMS_INSPECTOR_MONITOR_IND_CNF_SERVICE_STATE_ERR,
	AMS_INSPECTOR_MONITOR_IND_CNF_CALL_ID_ERR,
	AMS_INSPECTOR_MONITOR_IND_CNF_CALL_STATE_ERR,       
	                        
	AMS_INSPECTOR_MONITOR_IND_CNF_ORIGIN_TYPE_ERR,
	AMS_INSPECTOR_MONITOR_IND_CNF_ORIGIN_TELLER_ID_ERR,
	AMS_INSPECTOR_MONITOR_IND_CNF_ORIGIN_TELLER_STATE_ERR,
	AMS_INSPECTOR_MONITOR_IND_CNF_ORIGIN_TELLER_AMS_PID_ERR,
	AMS_INSPECTOR_MONITOR_IND_CNF_ORIGIN_TELLER_SERVICE_GROUP_ID_ERR,
	AMS_INSPECTOR_MONITOR_IND_CNF_ORIGIN_TELLER_SERVICE_STATE_ERR,	
	AMS_INSPECTOR_MONITOR_IND_CNF_OP_TYPE_ERR,
	AMS_INSPECTOR_MONITOR_IND_CNF_OP_STATE_ERR,	

	AMS_VTA_BANDWIDTH_NOTICE_PARA_ERR = (0x3600 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_VTA_BANDWIDTH_NOTICE_STATE_ERR, 
	AMS_VTA_BANDWIDTH_NOTICE_LEN_ERR,
	AMS_VTA_BANDWIDTH_NOTICE_TELLER_ID_ERR,
	AMS_VTA_BANDWIDTH_NOTICE_CALL_ID_ERR,
	AMS_VTA_BANDWIDTH_NOTICE_BANDWIDTH_PARA_ERR,	
	
	AMS_VTA_EVENT_NOTICE_PARA_ERR = (0x3700 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_VTA_EVENT_NOTICE_STATE_ERR,
	AMS_VTA_EVENT_NOTICE_LEN_ERR,
	AMS_VTA_EVENT_NOTICE_SERVICE_GROUP_ID_ERR, 
	AMS_VTA_EVENT_NOTICE_SERVICE_STATE_ERR,	
	AMS_VTA_EVENT_NOTICE_CALL_ID_ERR,  
	AMS_VTA_EVENT_NOTICE_CALL_STATE_ERR,
	AMS_VTA_EVENT_NOTICE_AMS_PID_ERR,
	AMS_VTA_EVENT_NOTICE_TELLER_ID_ERR,	
	AMS_VTA_EVENT_NOTICE_VTM_ID_ERR,
	AMS_VTA_EVENT_NOTICE_TYPE_ERR,	
	AMS_VTA_EVENT_NOTICE_LACK_FILE_INFO,    
	AMS_VTA_EVENT_NOTICE_FILE_PATH_LEN_ERR,	
	AMS_VTA_EVENT_NOTICE_FILE_NAME_LEN_ERR,	
	
	AMS_VTA_EVENT_NOTICE_SEND_FILE_TARGET_TYPE_ERR = (0x3720 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_VTA_EVENT_NOTICE_SEND_FILE_TARGET_TELLER_ID_ERR,
	AMS_VTA_EVENT_NOTICE_SEND_FILE_TARGET_TELLER_STATE_ERR,
	AMS_VTA_EVENT_NOTICE_SEND_FILE_TARGET_TELLER_AMS_PID_ERR,
	AMS_VTA_EVENT_NOTICE_SEND_FILE_TARGET_VTM_ID_ERR,
	AMS_VTA_EVENT_NOTICE_SEND_FILE_TARGET_VTM_STATE_ERR,
	AMS_VTA_EVENT_NOTICE_SEND_FILE_FILE_SEND_STATE_ERR,
	AMS_VTA_EVENT_NOTICE_SEND_FILE_START_TIMER_ERR,

	AMS_VTA_EVENT_NOTICE_RECV_FILE_PARA_ERR,
	AMS_VTA_EVENT_NOTICE_RECV_FILE_ORIGIN_TYPE_ERR,
	AMS_VTA_EVENT_NOTICE_RECV_FILE_ORIGIN_TELLER_ID_ERR,
	AMS_VTA_EVENT_NOTICE_RECV_FILE_ORIGIN_TELLER_AMS_PID_ERR,
	AMS_VTA_EVENT_NOTICE_RECV_FILE_ORIGIN_TELLER_SERVICE_GROUP_ID_ERR,
	AMS_VTA_EVENT_NOTICE_RECV_FILE_ORIGIN_TELLER_SERVICE_STATE_ERR,
	AMS_VTA_EVENT_NOTICE_RECV_FILE_ORIGIN_TELLER_STATE_ERR,
	AMS_VTA_EVENT_NOTICE_RECV_FILE_ORIGIN_VTM_ID_ERR,
	AMS_VTA_EVENT_NOTICE_RECV_FILE_ORIGIN_VTM_STATE_ERR,
	AMS_VTA_EVENT_NOTICE_RECV_FILE_FILE_RECV_STATE_ERR,

	AMS_VTA_EVENT_NOTICE_CANC_RECV_FILE_PARA_ERR,
	AMS_VTA_EVENT_NOTICE_CANC_RECV_FILE_ORIGIN_TYPE_ERR,
	AMS_VTA_EVENT_NOTICE_CANC_RECV_FILE_ORIGIN_TELLER_ID_ERR,
	AMS_VTA_EVENT_NOTICE_CANC_RECV_FILE_ORIGIN_TELLER_AMS_PID_ERR,
	AMS_VTA_EVENT_NOTICE_CANC_RECV_FILE_ORIGIN_TELLER_SERVICE_GROUP_ID_ERR,
	AMS_VTA_EVENT_NOTICE_CANC_RECV_FILE_ORIGIN_TELLER_SERVICE_STATE_ERR,
	AMS_VTA_EVENT_NOTICE_CANC_RECV_FILE_ORIGIN_TELLER_STATE_ERR,
	AMS_VTA_EVENT_NOTICE_CANC_RECV_FILE_ORIGIN_VTM_ID_ERR,
	AMS_VTA_EVENT_NOTICE_CANC_RECV_FILE_ORIGIN_VTM_STATE_ERR,
	AMS_VTA_EVENT_NOTICE_CANC_RECV_FILE_FILE_RECV_STATE_ERR,
	
	AMS_VTA_EVENT_NOTICE_AUDIO_REC_VTA_REPORT_FAIL= (0x3780 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_VTA_EVENT_NOTICE_UPLOAD_AUDIO_REC_FILE_VTA_REPORT_FAIL,
	AMS_VTA_EVENT_NOTICE_SCREEN_REC_VTA_REPORT_FAIL,
	AMS_VTA_EVENT_NOTICE_UPLOAD_SCREEN_REC_FILE_VTA_REPORT_FAIL,
	AMS_VTA_EVENT_NOTICE_SNAP_VTA_REPORT_FAIL,
	AMS_VTA_EVENT_NOTICE_DOWNLOAD_SNAP_FILE_VTA_REPORT_FAIL,
	AMS_VTA_EVENT_NOTICE_UPLOAD_FILE_VTA_REPORT_FAIL,
	AMS_VTA_EVENT_NOTICE_DOWNLOAD_FILE_VTA_REPORT_FAIL,
	AMS_VTA_EVENT_NOTICE_VTA_CANCEL_RECV_FILE_REPORT_FAIL,
	AMS_VTA_EVENT_NOTICE_REMOTE_COOP_VTA_REPORT_FAIL,
	
	AMS_VTA_PARA_CFG_IND_CNF_PARA_ERR = (0x3800 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_VTA_PARA_CFG_IND_CNF_STATE_ERR, 
	AMS_VTA_PARA_CFG_IND_CNF_LEN_ERR,
	AMS_VTA_PARA_CFG_IND_CNF_TELLER_ID_ERR,
	AMS_VTA_PARA_CFG_IND_CNF_SERVICE_GROUP_ID_ERR,
	AMS_VTA_PARA_CFG_IND_CNF_SERVICE_STATE_ERR,
	AMS_VTA_PARA_CFG_IND_CNF_OP_TYPE_ERR,
	AMS_VTA_PARA_CFG_IND_CNF_OP_STATE_ERR,
	AMS_VTA_PARA_CFG_IND_CNF_TERM_CONFIG_PARA_ERR,

	AMS_VTA_PARA_CFG_IND_CNF_VTA_REPORT_FAIL,
	AMS_VTA_PARA_CFG_IND_CNF_TIMEOUT,
	
	AMS_VTA_PARA_CFG_TIMEOUT_PARA_ERR = (0x3840 + AMS_VTA_QUEUE_MNG_REASON_BASE),
	AMS_VTA_PARA_CFG_TIMEOUT_LEN_ERR,
	AMS_VTA_PARA_CFG_TIMEOUT_TELLER_ID_ERR,
	AMS_VTA_PARA_CFG_TIMEOUT_TELLER_STATE_ERR,	
	AMS_VTA_PARA_CFG_TIMEOUT_SERVICE_GROUP_ID_ERR,
	AMS_VTA_PARA_CFG_TIMEOUT_SERVICE_STATE_ERR,
	AMS_VTA_PARA_CFG_TIMEOUT_OP_TYPE_ERR,	
	
	AMS_VTA_QUEUE_MNG_OTHER_FAIL = (0x3fff + AMS_VTA_QUEUE_MNG_REASON_BASE), //0x4fff

};

enum amsVtmMngResult
{
	AMS_VTM_MNG_SUCCESS = 0,

	AMS_VTM_LOGIN_PARA_ERR = AMS_VTM_MNG_REASON_BASE,
	AMS_VTM_LOGIN_STATE_ERR,
	AMS_VTM_LOGIN_NODE_RESOURCE_LIMITED,
	AMS_VTM_LOGIN_LEN_ERR,	
	AMS_VTM_LOGIN_VTM_NO_ERR,
	AMS_VTM_LOGIN_PWD_ERR,
	AMS_VTM_LOGIN_VNC_AUTH_PWD_ERR,
	AMS_VTM_LOGIN_LOGIN_REPEATEDLY,
	AMS_VTM_LOGIN_VTM_TYPE_ERR,	
	AMS_VTM_LOGIN_VTM_NUM_ERR,	
	AMS_VTM_LOGIN_FILE_SERVER_USR_NAME_ERR, 
	AMS_VTM_LOGIN_FILE_SERVER_USR_PWD_ERR, 
	AMS_VTM_LOGIN_ORG_ID_ERR,
	AMS_VTM_LOGIN_ORG_STATE_ERR,	
	AMS_VTM_LOGIN_LICENSE_TIMEOUT, //LIC
	AMS_VTM_LOGIN_VTM_NUM_BEYOND_LIC, //LIC
	
	AMS_VTM_LOGOUT_PARA_ERR = (0x0100 + AMS_VTM_MNG_REASON_BASE),
	AMS_VTM_LOGOUT_STATE_ERR, 
	AMS_VTM_LOGOUT_LEN_ERR,
	AMS_VTM_LOGOUT_VTM_ID_ERR,

	AMS_VTM_HANDSHAKE_PARA_ERR = (0x0200 + AMS_VTM_MNG_REASON_BASE),
	AMS_VTM_HANDSHAKE_STATE_ERR, 
	AMS_VTM_HANDSHAKE_LEN_ERR,
	AMS_VTM_HANDSHAKE_VTM_ID_ERR,
	AMS_VTM_HANDSHAKE_CLEAR_INACTIVTE_VTM,

	AMS_VTM_SEND_MSG_PARA_ERR = (0x0300+ AMS_VTM_MNG_REASON_BASE),
	AMS_VTM_SEND_MSG_STATE_ERR, 
	AMS_VTM_SEND_MSG_LEN_ERR,
	AMS_VTM_SEND_MSG_VTM_ID_ERR,
	AMS_VTM_SEND_MSG_TARGET_TYPE_ERR,
	AMS_VTM_SEND_MSG_TARGET_TELLER_ID_ERR,
	AMS_VTM_SEND_MSG_TARGET_TELLER_STATE_ERR,
	AMS_VTM_SEND_MSG_TARGET_TELLER_AMS_PID_ERR,	
	AMS_VTM_SEND_MSG_TARGET_VTM_ID_ERR,	
	AMS_VTM_SEND_MSG_TARGET_VTM_STATE_ERR,	
	AMS_VTM_SEND_MSG_MSG_LEN_ERR,
	AMS_VTM_SEND_MSG_MSG_SEND_STATE_ERR,	
	AMS_VTM_SEND_MSG_START_TIMER_ERR,

	AMS_VTM_RECV_MSG_PARA_ERR = (0x0340 + AMS_VTM_MNG_REASON_BASE),
	AMS_VTM_RECV_MSG_STATE_ERR, 
	AMS_VTM_RECV_MSG_LEN_ERR,
	AMS_VTM_RECV_MSG_VTM_ID_ERR,	
	AMS_VTM_RECV_MSG_ORIGIN_TYPE_ERR,         
	AMS_VTM_RECV_MSG_ORIGIN_TELLER_ID_ERR,       
	AMS_VTM_RECV_MSG_ORIGIN_TELLER_STATE_ERR, 
	AMS_VTM_RECV_MSG_ORIGIN_TELLER_AMS_PID_ERR,	
	AMS_VTM_RECV_MSG_ORIGIN_TELLER_SERVICE_GROUP_ID_ERR,
	AMS_VTM_RECV_MSG_ORIGIN_TELLER_SERVICE_STATE_ERR,
	AMS_VTM_RECV_MSG_ORIGIN_VTM_ID_ERR,    	
	AMS_VTM_RECV_MSG_ORIGIN_VTM_STATE_ERR,	 
	AMS_VTM_RECV_MSG_MSG_RECV_STATE_ERR,
	
	AMS_VTM_RECV_MSG_VTM_REPORT_FAIL,
	AMS_VTM_RECV_MSG_TIMEOUT,

	AMS_VTM_RECV_MSG_TIMEOUT_PARA_ERR = (0x0380 + AMS_VTM_MNG_REASON_BASE),                             
	AMS_VTM_RECV_MSG_TIMEOUT_LEN_ERR,                                                                                                                                     
	AMS_VTM_RECV_MSG_TIMEOUT_ORIGIN_TYPE_ERR,
	AMS_VTM_RECV_MSG_TIMEOUT_ORIGIN_TELLER_ID_ERR,
	AMS_VTM_RECV_MSG_TIMEOUT_ORIGIN_TELLER_STATE_ERR,
	AMS_VTM_RECV_MSG_TIMEOUT_ORIGIN_TELLER_AMS_PID_ERR,
	AMS_VTM_RECV_MSG_TIMEOUT_ORIGIN_TELLER_SERVICE_GROUP_ID_ERR,                         
	AMS_VTM_RECV_MSG_TIMEOUT_ORIGIN_TELLER_SERVICE_STATE_ERR,    	
	AMS_VTM_RECV_MSG_TIMEOUT_ORIGIN_VTM_ID_ERR,	
	AMS_VTM_RECV_MSG_TIMEOUT_ORIGIN_VTM_STATE_ERR,	     

	AMS_VTM_SEND_FILE_PARA_ERR = (0x0400 + AMS_VTM_MNG_REASON_BASE),
	AMS_VTM_SEND_FILE_STATE_ERR, 
	AMS_VTM_SEND_FILE_LEN_ERR,
	AMS_VTM_SEND_FILE_VTM_ID_ERR,
	AMS_VTM_SEND_FILE_TARGET_TYPE_ERR,
	AMS_VTM_SEND_FILE_TARGET_TELLER_ID_ERR,
	AMS_VTM_SEND_FILE_TARGET_TELLER_STATE_ERR,
	AMS_VTM_SEND_FILE_TARGET_TELLER_AMS_PID_ERR,
	AMS_VTM_SEND_FILE_TARGET_VTM_ID_ERR,	
	AMS_VTM_SEND_FILE_TARGET_VTM_STATE_ERR,		
	AMS_VTM_SEND_FILE_FILE_OP_TYPE_ERR,
	AMS_VTM_SEND_FILE_FILE_TYPE_ERR,
	AMS_VTM_SEND_FILE_FILE_PATH_ERR,
	AMS_VTM_SEND_FILE_FILE_NAME_ERR,	
	AMS_VTM_SEND_FILE_START_TIMER_ERR,

	AMS_VTM_SEND_FILE_FILE_SEND_STATE_ERR,

	AMS_VTM_RECV_FILE_PARA_ERR = (0x0440 + AMS_VTM_MNG_REASON_BASE),
	AMS_VTM_RECV_FILE_STATE_ERR, 
	AMS_VTM_RECV_FILE_LEN_ERR,
	AMS_VTM_RECV_FILE_VTM_ID_ERR,	
	AMS_VTM_RECV_FILE_ORIGIN_TYPE_ERR,
	AMS_VTM_RECV_FILE_ORIGIN_TELLER_ID_ERR,
	AMS_VTM_RECV_FILE_ORIGIN_TELLER_STATE_ERR,
	AMS_VTM_RECV_FILE_ORIGIN_TELLER_AMS_PID_ERR,
	AMS_VTM_RECV_FILE_ORIGIN_TELLER_SERVICE_GROUP_ID_ERR,
	AMS_VTM_RECV_FILE_ORIGIN_TELLER_SERVICE_STATE_ERR,	
	AMS_VTM_RECV_FILE_ORIGIN_VTM_ID_ERR,	
	AMS_VTM_RECV_FILE_ORIGIN_VTM_STATE_ERR,		
	AMS_VTM_RECV_FILE_FILE_RECV_STATE_ERR,

	AMS_VTM_RECV_FILE_VTM_REPORT_FAIL,
	AMS_VTM_RECV_FILE_TIMEOUT,
	
	AMS_VTM_RECV_FILE_TIMEOUT_PARA_ERR = (0x0480 + AMS_VTM_MNG_REASON_BASE),
	AMS_VTM_RECV_FILE_TIMEOUT_LEN_ERR,
	AMS_VTM_RECV_FILE_TIMEOUT_FILE_RECV_OP_ERR,
	AMS_VTM_RECV_FILE_TIMEOUT_FILE_SERVICE_TYPE_ERR,
	AMS_VTM_RECV_FILE_TIMEOUT_ORIGIN_TYPE_ERR,
	AMS_VTM_RECV_FILE_TIMEOUT_ORIGIN_TELLER_ID_ERR,
	AMS_VTM_RECV_FILE_TIMEOUT_ORIGIN_TELLER_STATE_ERR,
	AMS_VTM_RECV_FILE_TIMEOUT_ORIGIN_TELLER_AMS_PID_ERR,
	AMS_VTM_RECV_FILE_TIMEOUT_ORIGIN_TELLER_SERVICE_GROUP_ID_ERR,
	AMS_VTM_RECV_FILE_TIMEOUT_ORIGIN_TELLER_SERVICE_STATE_ERR,	
	AMS_VTM_RECV_FILE_TIMEOUT_ORIGIN_VTM_ID_ERR,
	AMS_VTM_RECV_FILE_TIMEOUT_ORIGIN_VTM_STATE_ERR,	

	AMS_VTM_FORCE_LOGIN_PARA_ERR = (0x0500 + AMS_VTM_MNG_REASON_BASE),
	AMS_VTM_FORCE_LOGIN_STATE_ERR,
	AMS_VTM_FORCE_LOGIN_NODE_RESOURCE_LIMITED,
	AMS_VTM_FORCE_LOGIN_LEN_ERR,	
	AMS_VTM_FORCE_LOGIN_VTM_NO_ERR,
	AMS_VTM_FORCE_LOGIN_PWD_ERR,
	AMS_VTM_FORCE_LOGIN_TERM_NET_INFO_ERR,
	AMS_VTM_FORCE_LOGIN_VNC_AUTH_PWD_ERR,
	AMS_VTM_FORCE_LOGIN_LOGIN_REPEATEDLY,
	AMS_VTM_FORCE_LOGIN_VTM_TYPE_ERR,	
	AMS_VTM_FORCE_LOGIN_VTM_NUM_ERR,	
	AMS_VTM_FORCE_LOGIN_FILE_SERVER_USR_NAME_ERR, 
	AMS_VTM_FORCE_LOGIN_FILE_SERVER_USR_PWD_ERR, 
	AMS_VTM_FORCE_LOGIN_LICENSE_TIMEOUT, //LIC
	AMS_VTM_FORCE_LOGIN_VTM_NUM_BEYOND_LIC, //LIC
	
	AMS_VTM_QUERY_INFO_PARA_ERR = (0x0f00 + AMS_VTM_MNG_REASON_BASE),
	AMS_VTM_QUERY_INFO_STATE_ERR, 
	AMS_VTM_QUERY_INFO_LEN_ERR,
	AMS_VTM_QUERY_INFO_VTM_ID_ERR,
	AMS_VTM_QUERY_INFO_CODE_ERR,
	AMS_VTM_QUERY_INFO_SERVICE_STATE_ERR,
	AMS_VTM_QUERY_INFO_CUSTOMER_PID_ERR,
	AMS_VTM_QUERY_INFO_CALC_QUEUE_INFO_ERR,			
		
	AMS_VTM_BANDWIDTH_NOTICE_PARA_ERR = (0x1000 + AMS_VTM_MNG_REASON_BASE),
	AMS_VTM_BANDWIDTH_NOTICE_STATE_ERR, 
	AMS_VTM_BANDWIDTH_NOTICE_LEN_ERR,
	AMS_VTM_BANDWIDTH_NOTICE_VTM_ID_ERR,	
	AMS_VTM_BANDWIDTH_NOTICE_CALL_ID_ERR,	
	AMS_VTM_BANDWIDTH_NOTICE_BANDWIDTH_PARA_ERR,
	
	AMS_VTM_EVENT_NOTICE_PARA_ERR = (0x1100 + AMS_VTM_MNG_REASON_BASE),
	AMS_VTM_EVENT_NOTICE_STATE_ERR,
	AMS_VTM_EVENT_NOTICE_LEN_ERR,
	AMS_VTM_EVENT_NOTICE_SERVICE_GROUP_ID_ERR, 
	AMS_VTM_EVENT_NOTICE_AMS_PID_ERR,
	AMS_VTM_EVENT_NOTICE_TELLER_ID_ERR,	
	AMS_VTM_EVENT_NOTICE_VTM_ID_ERR,
	AMS_VTM_EVENT_NOTICE_VTM_STATE_ERR,	
	AMS_VTM_EVENT_NOTICE_TYPE_ERR,	
	AMS_VTM_EVENT_NOTICE_CALL_ID_ERR,	
	AMS_VTM_EVENT_NOTICE_LACK_SERVICE_QUALITY,
	AMS_VTM_EVENT_NOTICE_LACK_FILE_INFO,
	AMS_VTM_EVENT_NOTICE_SERVICE_SCORE_ERR,
	AMS_VTM_EVENT_NOTICE_FILE_PATH_LEN_ERR,
	AMS_VTM_EVENT_NOTICE_FILE_NAME_LEN_ERR,
	
	AMS_VTM_EVENT_NOTICE_SEND_FILE_TARGET_TYPE_ERR = (0x1120 + AMS_VTM_MNG_REASON_BASE),
	AMS_VTM_EVENT_NOTICE_SEND_FILE_TARGET_TELLER_ID_ERR,
	AMS_VTM_EVENT_NOTICE_SEND_FILE_TARGET_TELLER_STATE_ERR,
	AMS_VTM_EVENT_NOTICE_SEND_FILE_TARGET_TELLER_AMS_PID_ERR,
	AMS_VTM_EVENT_NOTICE_SEND_FILE_TARGET_VTM_ID_ERR,
	AMS_VTM_EVENT_NOTICE_SEND_FILE_TARGET_VTM_STATE_ERR,
	AMS_VTM_EVENT_NOTICE_SEND_FILE_FILE_SEND_STATE_ERR,
	AMS_VTM_EVENT_NOTICE_SEND_FILE_START_TIMER_ERR,
	
	AMS_VTM_EVENT_NOTICE_RECV_FILE_PARA_ERR,
	AMS_VTM_EVENT_NOTICE_RECV_FILE_ORIGIN_TYPE_ERR,
	AMS_VTM_EVENT_NOTICE_RECV_FILE_ORIGIN_TELLER_ID_ERR,
	AMS_VTM_EVENT_NOTICE_RECV_FILE_ORIGIN_TELLER_STATE_ERR,
	AMS_VTM_EVENT_NOTICE_RECV_FILE_ORIGIN_TELLER_AMS_PID_ERR, 
	AMS_VTM_EVENT_NOTICE_RECV_FILE_ORIGIN_TELLER_SERVICE_GROUP_ID_ERR,
	AMS_VTM_EVENT_NOTICE_RECV_FILE_ORIGIN_TELLER_SERVICE_STATE_ERR,
	AMS_VTM_EVENT_NOTICE_RECV_FILE_ORIGIN_VTM_ID_ERR, 
	AMS_VTM_EVENT_NOTICE_RECV_FILE_ORIGIN_VTM_STATE_ERR,
	AMS_VTM_EVENT_NOTICE_RECV_FILE_FILE_RECV_STATE_ERR,

	AMS_VTM_EVENT_NOTICE_CANC_RECV_FILE_PARA_ERR,
	AMS_VTM_EVENT_NOTICE_CANC_RECV_FILE_ORIGIN_TYPE_ERR,
	AMS_VTM_EVENT_NOTICE_CANC_RECV_FILE_ORIGIN_TELLER_ID_ERR,
	AMS_VTM_EVENT_NOTICE_CANC_RECV_FILE_ORIGIN_TELLER_STATE_ERR,
	AMS_VTM_EVENT_NOTICE_CANC_RECV_FILE_ORIGIN_TELLER_AMS_PID_ERR, 
	AMS_VTM_EVENT_NOTICE_CANC_RECV_FILE_ORIGIN_TELLER_SERVICE_GROUP_ID_ERR,
	AMS_VTM_EVENT_NOTICE_CANC_RECV_FILE_ORIGIN_TELLER_SERVICE_STATE_ERR,
	AMS_VTM_EVENT_NOTICE_CANC_RECV_FILE_ORIGIN_VTM_ID_ERR, 
	AMS_VTM_EVENT_NOTICE_CANC_RECV_FILE_ORIGIN_VTM_STATE_ERR,
	AMS_VTM_EVENT_NOTICE_CANC_RECV_FILE_FILE_RECV_STATE_ERR,
	
	AMS_VTM_EVENT_NOTICE_SNAP_START_TIMER_ERR,
	
	AMS_VTM_EVENT_NOTICE_CUST_SCORING_VTM_REPORT_FAIL = (0x1180 + AMS_VTM_MNG_REASON_BASE),
	AMS_VTM_EVENT_NOTICE_REMOTE_COOP_VTM_REPORT_FAIL,
	AMS_VTM_EVENT_NOTICE_SNAP_VTM_REPORT_FAIL,
	AMS_VTM_EVENT_NOTICE_UPLOAD_SNAP_FILE_VTM_REPORT_FAIL,
	AMS_VTM_EVENT_NOTICE_UPLOAD_FILE_VTM_REPORT_FAIL,
	AMS_VTM_EVENT_NOTICE_DOWNLOAD_FILE_VTM_REPORT_FAIL,
	AMS_VTM_EVENT_NOTICE_VTM_CANCEL_RECV_FILE_REPORT_FAIL,
	

	AMS_VTM_PARA_CFG_IND_CNF_PARA_ERR = (0x1200 + AMS_VTM_MNG_REASON_BASE),
	AMS_VTM_PARA_CFG_IND_CNF_STATE_ERR, 
	AMS_VTM_PARA_CFG_IND_CNF_LEN_ERR,
	AMS_VTM_PARA_CFG_IND_CNF_VTM_ID_ERR,	
	AMS_VTM_PARA_CFG_IND_CNF_OP_TYPE_ERR,
	AMS_VTM_PARA_CFG_IND_CNF_OP_STATE_ERR,	
	AMS_VTM_PARA_CFG_IND_CNF_TERM_CONFIG_PARA_ERR,
	
	AMS_VTM_PARA_CFG_IND_CNF_VTM_REPORT_FAIL,	
	AMS_VTM_PARA_CFG_IND_CNF_TIMEOUT,
	
	AMS_VTM_PARA_CFG_TIMEOUT_PARA_ERR = (0x1240 + AMS_VTM_MNG_REASON_BASE),
	AMS_VTM_PARA_CFG_TIMEOUT_LEN_ERR,
	AMS_VTM_PARA_CFG_TIMEOUT_VTM_ID_ERR,	
	AMS_VTM_PARA_CFG_TIMEOUT_VTM_STATE_ERR,
	AMS_VTM_PARA_CFG_TIMEOUT_OP_TYPE_ERR,	
	
	AMS_VTM_MNG_OTHER_FAIL = (0x1fff + AMS_VTM_MNG_REASON_BASE), //0x6fff

};

enum amsCmsProcessResult
{
	AMS_CMS_PRCOESS_SUCCESS = 0,

	AMS_CMS_VTA_REG_PARA_ERR = AMS_CALL_REASON_BASE,
	AMS_CMS_VTA_REG_STATE_ERR,
	AMS_CMS_VTA_REG_LEN_ERR,	
	AMS_CMS_VTA_REG_TELLER_ID_ERR,	
	AMS_CMS_VTA_REG_RESOURCE_LIMITED,

	AMS_CMS_VTM_REG_PARA_ERR = (0x0100 + AMS_CALL_REASON_BASE), //0x0100
	AMS_CMS_VTM_REG_STATE_ERR,
	AMS_CMS_VTM_REG_LEN_ERR,	
	AMS_CMS_VTM_REG_VTM_ID_ERR,	
	AMS_CMS_VTM_REG_RESOURCE_LIMITED,
	
	AMS_CMS_GET_VTA_PARA_ERR = (0x0200 + AMS_CALL_REASON_BASE), //0x0200
	AMS_CMS_GET_VTA_LEN_ERR,	
	AMS_CMS_GET_VTA_AMS_PID_ERR,
	AMS_CMS_GET_VTA_CALL_ID_ERR,
	AMS_CMS_GET_VTA_TERMINAL_TYPE_ERR,	 
	AMS_CMS_GET_VTA_SERVICE_GROUP_ID_ERR,	
	AMS_CMS_GET_VTA_SERVICE_TYPE_ERR,
	AMS_CMS_GET_VTA_NO_VALID_SERVICE_GROUP_ID_OR_TYPE,

	AMS_CMS_GET_VTA_CALL_TYPE_ERR,  
	AMS_CMS_GET_VTA_ORIGIN_TELLER_ID_ERR,
	AMS_CMS_GET_VTA_ORIGIN_TELLER_STATE_ERR,
	AMS_CMS_GET_VTA_ORIGIN_TELLER_AMS_PID_ERR,
	AMS_CMS_GET_VTA_ORIGIN_TELLER_SERVICE_GROUP_ID_ERR,
	AMS_CMS_GET_VTA_ORIGIN_TELLER_SERVICE_STATE_ERR,	
	AMS_CMS_GET_VTA_TARGET_TYPE_ERR, 
	AMS_CMS_GET_VTA_TARGET_GROUP_ERR,
	AMS_CMS_GET_VTA_TARGET_TELLER_ID_ERR,
	AMS_CMS_GET_VTA_TARGET_TELLER_STATE_ERR,
	AMS_CMS_GET_VTA_VTM_ID_ERR,
	AMS_CMS_GET_VTA_ASSOC_CALL_ID_ERR,

	AMS_CMS_GET_VTA_LICENSE_TIMEOUT, //LIC
	AMS_CMS_GET_VTA_TPS_BEYOND_LIC,//LIC
	
	AMS_CMS_GET_VTA_SERVICE_IN_QUEUE = (0x0300 + AMS_CALL_REASON_BASE),//0x0300 0x7300
	AMS_CMS_GET_VTA_SERVICE_INTELLIGENT_ROUTING_ERR,
	
	AMS_CMS_GET_VTA_SIR_VTMNO_ERR,// SIR SERVICE_INTELLIGENT_ROUTING
	AMS_CMS_GET_VTA_SIR_SERVICE_GROUP_ID_ERR,
	AMS_CMS_GET_VTA_SIR_CALL_TYPE_ERR,
	AMS_CMS_GET_VTA_SIR_VTA_EMPTY,
	AMS_CMS_GET_VTA_SIR_CALC_QUEUE_INFO_ERR,
	AMS_CMS_GET_VTA_SIR_TOO_MANY_CUSTOMER_IN_QUEUE, 
	AMS_CMS_GET_VTA_SIR_TARGET_TELLER_NOT_LOGIN,
	AMS_CMS_GET_VTA_SIR_TARGET_TELLER_NOT_REGISTERED,
	AMS_CMS_GET_VTA_SIR_TARGET_TELLER_STATE_ERR,
	AMS_CMS_GET_VTA_SIR_CALL_TRANSFER_TOO_MANY_TIMES,
	AMS_CMS_GET_VTA_ORG_ID_ERR,
	AMS_CMS_GET_VTA_ORG_POS_ERR,
	AMS_CMS_GET_VTA_PARENT_ORG_ID_ERR,
	AMS_CMS_GET_VTA_SELECT_SERVICE_GROUP_ID_ERR,
	
	AMS_CMS_GET_VTA_LP_RESOURCE_LIMITED,
	AMS_CMS_GET_VTA_CREATE_TIMER_ERR,
	AMS_CMS_GET_VTA_TIMEOUT,
	
	AMS_CMS_GET_VTA_TIMEOUT_PARA_ERR = (0x0400 + AMS_CALL_REASON_BASE),
	AMS_CMS_GET_VTA_TIMEOUT_STATE_ERR,
	AMS_CMS_GET_VTA_TIMEOUT_LEN_ERR,		
	AMS_CMS_GET_VTA_TIMEOUT_VTM_ID_ERR,
	AMS_CMS_GET_VTA_TIMEOUT_SERVICE_STATE_ERR,
	
	AMS_CMS_QUERY_TERM_NETINFO_PARA_ERR = (0x0500 + AMS_CALL_REASON_BASE),
	AMS_CMS_QUERY_TERM_NETINFO_STATE_ERR, 
	AMS_CMS_QUERY_TERM_NETINFO_LEN_ERR,
	AMS_CMS_QUERY_TERM_NETINFO_TELLER_ID_ERR,
	AMS_CMS_QUERY_TERM_NETINFO_VTM_ID_ERR,
	AMS_CMS_QUERY_TERM_NETINFO_TERMINAL_TYPE_ERR,
	
	AMS_CMS_EVENT_NOTICE_PARA_ERR = (0x0600 + AMS_CALL_REASON_BASE),
	AMS_CMS_EVENT_NOTICE_STATE_ERR, 
	AMS_CMS_EVENT_NOTICE_SERVICE_GROUP_ID_ERR, 
	AMS_CMS_EVENT_NOTICE_SERVICE_STATE_ERR, 
	AMS_CMS_EVENT_NOTICE_LEN_ERR,
	AMS_CMS_EVENT_NOTICE_AMS_PID_ERR,
	AMS_CMS_EVENT_NOTICE_CALL_ID_ERR,	
	AMS_CMS_EVENT_NOTICE_TELLER_ID_ERR,
	AMS_CMS_EVENT_NOTICE_VTM_ID_ERR,
	AMS_CMS_EVENT_NOTICE_CODE_ERR,
	AMS_CMS_EVENT_NOTICE_VTA_STATE_ERR,
	AMS_CMS_EVENT_NOTICE_VTM_STATE_ERR,	
	
	AMS_CMS_EVENT_NOTICE_ORIGIN_TELLER_ID_ERR,
	AMS_CMS_EVENT_NOTICE_ORIGIN_TELLER_STATE_ERR,
	AMS_CMS_EVENT_NOTICE_ORIGIN_TELLER_AMS_PID_ERR,
	AMS_CMS_EVENT_NOTICE_ORIGIN_TELLER_SERVICE_GROUP_ID_ERR,
	AMS_CMS_EVENT_NOTICE_ORIGIN_TELLER_SERVICE_STATE_ERR,

	AMS_CMS_HANDSHAKE_CLEAR_INACTIVTE_CALL,
	
	AMS_CMS_EVENT_IND_CNF_PARA_ERR = (0x0700 + AMS_CALL_REASON_BASE),
	AMS_CMS_EVENT_IND_CNF_STATE_ERR, 
	AMS_CMS_EVENT_IND_CNF_LEN_ERR,
	AMS_CMS_EVENT_IND_CNF_AMS_PID_ERR,
	AMS_CMS_EVENT_IND_CNF_CALL_ID_ERR,
	AMS_CMS_EVENT_IND_CNF_TELLER_ID_ERR,
	AMS_CMS_EVENT_IND_CNF_VTM_ID_ERR,	
	AMS_CMS_EVENT_IND_CNF_TELLER_STATE_ERR,	
	AMS_CMS_EVENT_IND_CNF_TELLER_UPDATE_STATE_ERR,		
	AMS_CMS_EVENT_IND_CNF_VTM_STATE_ERR,	
	AMS_CMS_EVENT_IND_CNF_CODE_ERR,
	AMS_CMS_EVENT_IND_CNF_CMS_REPORT_FAIL,

	AMS_CMS_EVENT_IND_TIMEOUT_PARA_ERR = (0x0740  + AMS_CALL_REASON_BASE),
	AMS_CMS_EVENT_IND_TIMEOUT_STATE_ERR, 
	AMS_CMS_EVENT_IND_TIMEOUT_LEN_ERR,
	AMS_CMS_EVENT_IND_TIMEOUT_AMS_PID_ERR,
	AMS_CMS_EVENT_IND_TIMEOUT_CALL_ID_ERR,
	AMS_CMS_EVENT_IND_TIMEOUT_TELLER_ID_ERR,
	AMS_CMS_EVENT_IND_TIMEOUT_VTM_ID_ERR,	
	AMS_CMS_EVENT_IND_TIMEOUT_TELLER_STATE_ERR,		
	AMS_CMS_EVENT_IND_TIMEOUT_VTM_STATE_ERR,	
	AMS_CMS_EVENT_IND_TIMEOUT_CODE_ERR,	
	AMS_CMS_EVENT_IND_TIMEOUT_SERVICE_GROUP_ID_ERR,	
	AMS_CMS_EVENT_IND_TIMEOUT_SERVICE_STATE_ERR,	

	AMS_CMS_PROCESS_OTHER_FAIL = (0x0fff  + AMS_CALL_REASON_BASE), //0x7fff

};

enum amsRcasProcessResult
{
	AMS_RCAS_PRCOESS_SUCCESS = 0,

};


enum amsTellerType
{
	AMS_TELLER_VTA                           = 0,
	AMS_TELLER_MANAGER                       = 1,
	AMS_TELLER_INSPECTOR                     = 2,
	AMS_TELLER_MAX,
};



//zry added for scc 2018
#ifdef ecc
enum amsTerminalType
{
	AMS_TERMINAL_RSVD						= 0,

	AMS_TERMINAL_ROBOT						= 1,
	AMS_TERMINAL_TELLER						= 2,
	AMS_TERMINAL_MOBILEPHONE				= 3,
	AMS_TERMINAL_PC							= 4,

	AMS_TERMINAL_MAX
};
#else
enum amsTerminalType
{
	AMS_TERMINAL_RSVD                        = 0,

	AMS_TERMINAL_VTA                         = 1,
	AMS_TERMINAL_VTM                         = 2,
	AMS_TERMINAL_MOBILEPHONE                 = 3,
	AMS_TERMINAL_PC                          = 4,

	AMS_TERMINAL_MAX,
};
#endif



enum amsSeatServiceFlag
{
	AMS_SEAT_UNINSTALL                     = 0,
	AMS_SEAT_INSTALL                       = 1,
};

//added end


enum amsTellerServiceFlag
{
	AMS_TELLER_UNINSTALL                     = 0,
	AMS_TELLER_INSTALL                       = 1,
};

enum amsVtmFlag
{
	AMS_VTM_UNINSTALL                        = 0,
	AMS_VTM_INSTALL                          = 1,
};

enum amsOrgFlag
{
	AMS_ORG_UNINSTALL                        = 0,
	AMS_ORG_INSTALL                          = 1,	
};

enum amsRcasFlag
{
	AMS_RCAS_UNINSTALL                       = 0,
	AMS_RCAS_INSTALL                         = 1,
};

enum amsQueueFlag
{
	AMS_QUEUE_NOT_CFG                        = 0,
	AMS_QUEUE_CFG                            = 1,
};

enum amsTellerAnswerType
{
	AMS_MANUAL_ANSWER                        = 0,
	AMS_AUTO_ANSWER                          = 1,
};

enum amsTellerRegisterFlag
{
	AMS_TELLER_UNREGISTER                    = 0,
	AMS_TELLER_REGISTER                      = 1,
};

enum amsVtmRegisterFlag
{
	AMS_VTM_UNREGISTER                       = 0,
	AMS_VTM_REGISTER                         = 1,
};
/*
enum amsSrvGrpId
{
	AMS_SERVICE_GROUP_SYS_MAINTENANCE        = 0,
	AMS_SERVICE_GROUP_VIP                    = 1,
	AMS_SERVICE_GROUP_FINANCIAL_MANAGEMENT   = 2,
	AMS_SERVICE_GROUP_COMMON                 = 3,
	
	AMS_SERVICE_GROUP_ID_MAX,
};
*/
enum amsServiceGroupFlag
{
	AMS_SERVICE_GROUP_UNINSTALL              = 0,
	AMS_SERVICE_GROUP_INSTALL                = 1,	
};

enum amsServiceState
{
	AMS_SERVICE_INACTIVE = 0,
	AMS_SERVICE_ACTIVE,
};

enum amsServiceFlag
{
	AMS_SERVICE_UNINSTALL                    = 0,
	AMS_SERVICE_INSTALL                      = 1,	
};

enum amsServiceType
{
	AMS_SERVICE_SYSTEM_MAINTENANCE           = 0x00000001, //BIT 1
	AMS_SERVICE_ACTIVATE_CARDS               = 0x00000002, //BIT 2
	AMS_SERVICE_FINANCIAL_MANAGEMENT         = 0x00000004, //BIT 3
	AMS_SERVICE_TRANSFER_ACCOUNTS            = 0x00000008, //BIT 4
	AMS_SERVICE_LOADS                        = 0x00000010, //BIT 5
	AMS_SERVICE_CREDIT_CARD                  = 0x00000020, //BIT 6
	AMS_SERVICE_MONITOR                      = 0x00000040, //BIT 7
	AMS_SERVICE_MAX                          = 0X80000000, //64BIT
};

enum amsOrgState
{
	AMS_ORG_STATE_RSVD = 0,
	AMS_ORG_ACTIVE,
	AMS_ORG_INACTIVE,	
	
	AMS_ORG_DEBUG,	
	AMS_ORG_APPLY,
	AMS_ORG_ABANDON,
	
};

enum amsRecResult
{
	AMS_REC_PROC_SUCCESS = 0,
	
};

enum amsStateType
{
	AMS_STATE_NULL = 0,
	AMS_VTA_STATE,		
	AMS_CALL_STATE,
	AMS_VTM_STATE,
	AMS_CUSTOMER_STATE,
};

//zry added for scc 2018
#ifdef scc
enum amsSeatState
{
	AMS_SEAT_STATE_IDLE = 0,
	AMS_SEAT_STATE_BUSY,
	AMS_SEAT_STATE_REST,
	AMS_SEAT_STATE_PREPARE,
	AMS_SEAT_STATE_OFFLINE,
//	AMS_VTA_STATE_LEAVE,
	
	AMS_SEAT_STATE_RSVD, 	//AMS_VTA_STATE_RSVD 5
}

#else
enum amsVtaState
{
	AMS_VTA_STATE_IDLE = 0,
	AMS_VTA_STATE_BUSY,
	AMS_VTA_STATE_REST,
	AMS_VTA_STATE_PREPARE,
	AMS_VTA_STATE_OFFLINE,
//	AMS_VTA_STATE_LEAVE,
	
	AMS_VTA_STATE_RSVD,  	//AMS_VTA_STATE_RSVD 5
};
#endif
#added end

enum amsCallState
{
	AMS_CALL_STATE_NULL = 0,
	AMS_CALL_STATE_WAIT_ANSWER,
	AMS_CALL_STATE_TRANSFER,
	AMS_CALL_STATE_ANSWER,
	AMS_CALL_STATE_HOLD,	
	AMS_CALL_STATE_INNER_CALL,
	AMS_CALL_STATE_MONITOR_CALL,
	AMS_CALL_STATE_CONF,

	AMS_CALL_STATE_RSVD,  //AMS_CALL_STATE_RSVD 6

};

enum amsRcasState
{
	AMS_RCAS_INACTIVE = 0,
	AMS_RCAS_ACTIVE,
};

enum amsVtmState
{
	AMS_VTM_STATE_IDLE = 0,
	AMS_VTM_STATE_BUSY,
	AMS_VTM_STATE_OFFLINE,

	AMS_VTM_STATE_RSVD
};


//zry added for scc 2018
enum amsUserState
{
	AMS_USER_STATE_IDLE=0,
	AMS_USER_STATE_BUSY,
	AMS_USER_STATE_OFFLINE,
	AMS_USER_STATE_RSVD
};
//added end

enum amsCustomerServiceState
{
	AMS_CUSTOMER_SERVICE_NULL                  = 0,

	AMS_CUSTOMER_IN_QUEUE                      = 1,
	AMS_CUSTOMER_IN_SERVICE                    = 2,	

	AMS_CUSTOMER_SERVICE_RSVD,
};

enum amsStateSetState
{
	AMS_STATE_SET_NULL = 0,
	AMS_STATE_SETTING,
};

enum amsAudioRecordState
{
	AMS_AUDIO_RECORD_NULL = 0,
	AMS_AUDIO_RECORDING,
};

enum amsScreenRecordState
{
	AMS_SCREEN_RECORD_NULL = 0,
	AMS_SCREEN_RECORDING,	
};

enum amsRemoteCoopTargetType
{
	AMS_REMOTE_COOP_TARGET_RSVD                = 0,

	AMS_REMOTE_COOP_TARGET_RCAS                = 1,
	AMS_REMOTE_COOP_TARGET_VTM                 = 2,	
	AMS_REMOTE_COOP_TARGET_RCAS_VTM            = 3,
	
	AMS_REMOTE_COOP_TARGET_MAX,
};

enum amsRemoteCooperativeState
{
	AMS_DESKTOP_SHARE_NULL = 0,
	AMS_DESKTOP_SHARE_STARTING,
	AMS_DESKTOP_SHARING,
	AMS_DESKTOP_CONTROL_STARTING,
	AMS_DESKTOP_CONTROLLING,
	AMS_DESKTOP_CONTROL_STOPPING,
	AMS_DESKTOP_SHARE_STOPPING,

};

enum amsSnapState
{
	AMS_SNAP_NULL = 0,
	AMS_SNAP_STARTING,
	AMS_SNAP_UPLOADING,
	AMS_SNAP_UPLOADED,
	AMS_SNAP_DOWNLOADING,
	
};

enum amsOperateOriginType
{
	AMS_OPERATE_ORIGIN_RSVD                    = 0,

	AMS_OPERATE_ORIGIN_VTA                     = 1,
	AMS_OPERATE_ORIGIN_VTM                     = 2,	

	AMS_OPERATE_ORIGIN_MAX,
};

enum amsOperateTargetType
{
	AMS_OPERATE_TARGET_RSVD                    = 0,

	AMS_OPERATE_TARGET_VTA                     = 1,
	AMS_OPERATE_TARGET_VTM                     = 2,	

	AMS_OPERATE_TARGET_MAX,
};

enum amsSendMsgState
{
	AMS_SEND_MSG_NULL = 0,
	AMS_MSG_SENDING,
//	AMS_MSG_RECEIVING,	
};

enum amsSendFileState
{
	AMS_SEND_FILE_NULL = 0,
	AMS_SEND_FILE_UPLOADING,
	AMS_SEND_FILE_UPLOADED,
	AMS_SEND_FILE_DOWNLOADING,
};

enum amsMultiSessState
{
	AMS_MULTI_SESS_NULL = 0,
	AMS_MULTI_SESS_STARTING,
	AMS_IN_MULTI_SESS,
	AMS_MULTI_SESS_STOPPING,
};

enum amsMonitorState
{
	AMS_MONITOR_NULL = 0,
	AMS_MONITROR_STARTING,
	AMS_MONITRORING,
	AMS_FORCE_INSERT_CALL_STARTING,
	AMS_IN_CALL_BY_FORCE_INSERT,
	AMS_FORCE_INSERT_CALL_STOPPING,
	AMS_MONITROR_STOPPING,
};

enum amsTermParaCfgState
{
	AMS_TERM_PARA_CFG_NULL = 0,
	AMS_TERM_PARA_CFG_STARTING,
};

enum vtaStateOperateCode
{
	VTA_STATE_OPERATE_RSVD                     = 0,

	VTA_STATE_OPERATE_IDLE                     = 1,
	VTA_STATE_OPERATE_BUSY                     = 2,	
	VTA_STATE_OPERATE_REST                     = 3,
	VTA_STATE_OPERATE_CANCEL_REST              = 4,
	VTA_STATE_OPERATE_PREPARE                  = 5,
	VTA_STATE_OPERATE_PREPARE_COMPLETELY       = 6,
//	VTA_STATE_OPERATE_LEAVE                    = 7,	
	
	VTA_STATE_OPERATE_MAX,
};

enum vtaStateOperateIndCode
{
	VTA_STATE_OPERATE_IND_RSVD                 = 0,
		
	VTA_STATE_OPERATE_IND_IDLE                 = 1,
	VTA_STATE_OPERATE_IND_BUSY                 = 2,
	VTA_STATE_OPERATE_IND_REST                 = 3,
	VTA_STATE_OPERATE_IND_CANCEL_REST          = 4,
	VTA_STATE_OPERATE_IND_PREPARE              = 5,
	VTA_STATE_OPERATE_IND_PREPARE_COMPLETELY   = 6,
	VTA_STATE_OPERATE_IND_OFFLINE              = 7,
	
	VTA_STATE_OPERATE_IND_MAX,
};

enum vtaStateOperateReason
{
	VTA_STATE_OPERATE_REASON_RSVD              = 0,
		
	VTA_STATE_OPERATE_BUSY_IN_CALL             = 1,
	VTA_STATE_OPERATE_BUSY_SET_BYT_TELLER      = 2,
	VTA_STATE_OPERATE_BUSY_SET_BYT_MANAGER     = 3,
	
	VTA_STATE_OPERATE_REASON_MAX,
};


enum amsTellerQueryInfoType
{
	AMS_VTA_QUERY_VTA_INFO_RSVD                = 0,
	AMS_VTA_QUERY_ALL_TELLER_STATE_INFO        = 1,	
	AMS_VTA_QUERY_TELLER_STATE_INFO            = 2,	
	AMS_VTA_QUERY_TELLER_SERVICE_LIST          = 3,	
	AMS_VTA_QUERY_SERVICE_TELLER_LIST          = 4,	
	AMS_VTA_QUERY_SERVICE_QUEUE_INFO           = 5,	
	AMS_VTA_QUERY_SERVICE_GROUP_ID_QUEUE_INFO     = 6,		
	AMS_VTA_QUERY_CUR_TELLER_SERVICE_LIST      = 7,		
	AMS_VTA_QUERY_CUR_TELLER_WORK_INFO         = 8,		
	AMS_VTA_QUERY_TELLER_LIST_BY_NO_KEY        = 9,		
	AMS_VTA_QUERY_TELLER_LIST_BY_NAME_KEY      = 10,	
	
	AMS_VTA_QUERY_TYPE_MAX,
};


enum amsFileType
{
	AMS_FILE_AUTO                              = 0,

	AMS_FILE_RM                                = 1,
	AMS_FILE_WAV                               = 2,
	AMS_FILE_MP3                               = 3,
	AMS_FILE_FLV                               = 4,
	AMS_FILE_FBS                               = 5,
	
	AMS_FILE_JPG                               = 20,

	AMS_FILE_MAX,
};


enum amsCallType
{
	AMS_CALL_VTM_TO_VTA                        = 0,
	AMS_CALL_INNER                             = 1,
	AMS_CALL_TRANSFER                          = 2,
	AMS_CALL_MONITOR                           = 3,

	AMS_CALL_TYPE_MAX,
};

enum amsCallTargetType
{
	AMS_CALL_GROUP                             = 0,
	AMS_CALL_TELLER                            = 1,

	AMS_CALL_TARGET_MAX,
};

enum vtaVolumeCtrlType
{
	VTA_VOLUME_CTRL_RSVD                       = 0,

	VTA_VOLUME_MUTE                            = 1,
	VTA_VOLUME_UNMUTE                          = 2,	
	VTM_VOLUME_MUTE                            = 3,
	VTM_VOLUME_UNMUTE                          = 4,		
//	VTA_VOLUME_UP                              = 5,
//	VTA_VOLUME_DOWN                            = 6,

	VTA_VOLUME_CTRL_MAX,
};


enum vtaAudioRecordOperateCode
{
	VTA_AUDIO_REC_OPERATE_RSVD                 = 0,

	VTA_START_AUDIO_RECORD                     = 1,
	VTA_STOP_AUDIO_RECORD                      = 2,	
//	VTA_PLAY_AUDIO_RECORD                      = 3,
//	VTA_STOP_PLAY_AUDIO_RECORD                 = 4,

	VTA_AUDIO_REC_OPERATE_MAX,
};


enum vtaScreenRecordOperateCode
{
	VTA_SCREEN_REC_OPERATE_RSVD                = 0,

	VTA_START_SCREEN_RECORD                    = 1,
	VTA_STOP_SCREEN_RECORD                     = 2,	

	VTA_SCREEN_REC_OPERATE_MAX,
};


enum vtaRemoteOperateCode
{
	VTA_REMOTE_OPERATE_RSVD                    = 0,

	VTA_START_SCREEN_SHARE                     = 1,
	VTA_STOP_SCREEN_SHARE                      = 2,	
	VTA_START_SCREEN_CTRL                      = 3,
	VTA_STOP_SCREEN_CTRL                       = 4,

	VTA_REMOTE_OPERATE_MAX,
};

enum vtaSnapOperateCode
{
	VTA_SNAP_OPERATE_RSVD                      = 0,

	VTA_SNAP_ONCE                              = 1,
	VTA_SNAP_CONTINUOUS                        = 2,	

	VTA_SNAP_OPERATE_MAX,
};

enum amsFileSrvType
{
	AMS_FILE_SERVICE_RSVD                      = 0,

	AMS_AUDIO_REC_FILE                         = 1,
	AMS_SCREEN_REC_FILE                        = 2,
	AMS_SNAP_FILE                              = 3,
	AMS_COMM_SERVICE_FILE                      = 4,

	AMS_FILE_SERVICE_TYPE_MAX,
};

enum amsFileUser
{
	AMS_FILE_USER_RSVD                         = 0,

};

enum vtaFileSendOperateCode
{
	VTA_FILE_SEND_OPERATE_RSVD                 = 0,

	VTA_FILE_SEND                              = 1,
	VTA_CANCEL_FILE_SEND                       = 2,	

	VTA_FILE_SEND_OPERATE_MAX,
};

enum vtaFileRecvOperateCode
{
	VTA_FILE_RECV_OPERATE_RSVD                 = 0,

	VTA_FILE_RECV                              = 1,
	VTA_CANCEL_FILE_RECV                       = 2,	

	VTA_FILE_RECV_OPERATE_MAX,
};

enum vtaMultiSessOperateCode
{
	VTA_MULTI_SESS_OPERATE_RSVD                 = 0,

	VTA_START_MULTI_SESS                        = 1,
	VTA_STOP_MULI_SESS                          = 2,	

	VTA_MULTI_SESS_OPERATE_MAX,
};

enum vtaMonitorOperateCode
{
	VTA_MONITOR_OPERATE_RSVD                   = 0,

	VTA_START_MONITOR                          = 1,
	VTA_STOP_MONITOR                           = 2,	
	VTA_START_FORCE_INSERT_CALL                = 3,
	VTA_STOP_FORCE_INSERT_CALL                 = 4,	
	
	VTA_MONITOR_OPERATE_MAX,
};

enum amsTermParaCfgCode
{
	AMS_PARA_CONFIG_RSVD                       = 0,

	AMS_CONFIG_FILE_SERVER_PARA                = 1,
	AMS_CONFIG_TERM_PARA                       = 2,	
	AMS_CONFIG_ADD_ID_NO                       = 3,	
	AMS_CONFIG_MODIFY_ID_NO                    = 4,	
	AMS_CONFIG_DELETE_ID_NO                    = 5,	
	AMS_CONFIG_ORDINARY_FILE_PATH              = 6,	
	AMS_CONFIG_ENCRYPT_INFO                    = 7,	
	AMS_CONFIG_NET_TRAVERSAL_INFO              = 8,	
	
	AMS_QUERY_TERM_CONFIG_PARA                 = 0x10,	
	
	AMS_PARA_CONFIG_MAX,
};

enum amsTransType
{
	AMS_TRANS_TYPE_RSVD                        = 0,

	AMS_TRANS_TCP_SERVER                       = 1,
	AMS_TRANS_TCP_CLIENT                       = 2,	

	AMS_TRANS_TYPE_MAX,
};

enum amsParaId
{
	AMS_ID_NULL                                = 0x00,

	AMS_TELLER_LOGIN_INFO_ID                   = 0x01,
	AMS_TERM_NET_INFO_ID                       = 0x02, 
	AMS_DIGITS_INFO_ID                         = 0x03,
	AMS_TIME_INFO_ID                           = 0x04,
	AMS_TEXT_INFO_ID                           = 0x05,
	AMS_FILE_INFO_ID                           = 0x06,
	AMS_TELLER_WORK_INFO_ID                    = 0x07,
	AMS_CALL_TARGET_ID                         = 0x08,
	AMS_QUEUE_RULE_ID                          = 0x09,
	AMS_SERVICE_QUALITY_ID                     = 0x0a,
//	AMS_ASSOC_CALL_ID                          = 0x0b,
	AMS_RSVD_PARA_ID                           = 0x0c,
	AMS_FILE_SERVER_PARA_ID                    = 0x0d,
	AMS_STATE_OP_INFO_ID                       = 0x0e,
	AMS_TERM_CONF_PARA_ID                      = 0x0f,
	
	AMS_LOGIN_STATE_ID                         = 0x10,	
	AMS_CALL_REL_STATE_ID                      = 0x11,
	AMS_ANSWER_TYPE_ID                         = 0x12,

	AMS_TERM_ID_NO_ID                          = 0x13,
	AMS_TELLER_STATE_INFO_ID                   = 0x14,
	AMS_QUEUE_INFO_ID                          = 0x15,
	AMS_SERVICE_LIST_ID                        = 0x16,
	AMS_TELLER_LIST_ID                         = 0x17,
	AMS_ORDINARY_FILE_PATH_ID                  = 0x18,
	AMS_ENCRYPT_INFO_ID                        = 0x19,
	AMS_NET_TRAVERSAL_INFO_ID                  = 0x1a,
	
	AMS_RFB_INIT_PARA_ID                       = 0x40,
	AMS_TRANS_PROTO_PARA_ID                    = 0x41,
	AMS_SECURITIES_PARA_ID                     = 0x42,
	AMS_VNC_AUTH_PARA_ID                       = 0x43,
	AMS_PIXEL_FORMAT_PARA_ID                   = 0x44,
	AMS_ENCODING_PARA_ID                       = 0x45,
	AMS_RCAS_CAP_PARA_ID                       = 0x46,
	
	AMS_ID_MAX,
};

enum amsTimerType_t
{
	T_AMS_TIMER_NULL = 0,
		
	T_AMS_VTA_STATE_OPERATE_IND_TIMER,
	T_AMS_CALL_EVENT_IND_TIMER,
	T_AMS_CUSTOMER_IN_QUEUE_TIMER,	
	T_AMS_VOLUME_CTRL_TIMER,
	T_AMS_RCAS_REMOTE_COOP_TIMER,	
	T_AMS_VTM_REMOTE_COOP_TIMER,		
	T_AMS_SNAP_TIMER,
	T_AMS_REST_TIMER,
	T_AMS_VTA_RECV_MSG_TIMER,
	T_AMS_VTM_RECV_MSG_TIMER,
	T_AMS_VTA_RECV_FILE_TIMER,
	T_AMS_VTM_RECV_FILE_TIMER,	
	T_AMS_MULTI_SESS_TIMER,
	T_AMS_MONITOR_TIMER,
	T_AMS_VTA_PARA_CFG_TIMER,	
	T_AMS_VTM_PARA_CFG_TIMER,
	
	T_AMS_PARA_CFG_TIMER,
	
	T_AMS_TIMER_MAX,
};

enum amsTimerStatType_t
{
	AMS_CREATE_TIMER = 0,
	AMS_KILL_TIMER,
	AMS_TIMER_TIMEOUT,
};

enum amsResponseType
{
	AMS_TEMP_RESPONSE                           = 0,

	AMS_CONFIRM_RESPONSE                        = 1,
	
	AMS_RESPONSE_TYPE_MAX,
};


enum amsVtmQueryInfoType
{
	AMS_VTM_QUERY_VTM_INFO_RSVD                = 0,
	AMS_VTM_QUERY_VTM_QUEUE_INFO               = 1,	
	AMS_VTM_QUERY_TYPE_MAX,
};

enum amsTellerEventNoticeCode
{
	AMS_TELLER_EVENT_NOTICE_RSVD                = 0,

	AMS_TELLER_AUDIO_REC_EVENT_REPORT           = 1,
	AMS_TELLER_AUDIO_REC_FILE_UPLOAD            = 2,	
	AMS_TELLER_SCREEN_REC_EVENT_REPORT          = 3,
	AMS_TELLER_SCREEN_REC_FILE_UPLOAD           = 4,		
	AMS_TELLER_SNAP_EVENT_REPORT                = 5,
	AMS_TELLER_SNAP_FILE_DOWNLOAD               = 6,
	AMS_TELLER_FILE_UPLOAD                      = 7,
	AMS_TELLER_FILE_DOWNLOAD                    = 8,
	AMS_TELLER_CANCEL_RECV_FILE                 = 9,	
	AMS_TELLER_SCREEN_SHARE_EVENT_REPORT        = 10,	
	
	AMS_TELLER_EVENT_NOTICE_MAX,
};

enum amsTellerEventIndCode
{
	AMS_TELLER_EVENT_IND_RSVD                   = 0,

	AMS_TELLER_REST_TIMEOUT                     = 1,
	AMS_TELLER_SCREEN_SHARE_ABORT               = 2,
	AMS_TELLER_VTM_SNAP_ABORT                   = 3,
	AMS_TELLER_REMOTE_CANCEL_RECV_FILE          = 4,
	
	AMS_TELLER_EVENT_IND_MAX,
};


enum vtmVolumeCtrlIndCode
{
	VTM_VOLUME_CTRL_IND_RSVD                   = 0,

	VTM_VOLUME_MUTE_IND                        = 1,
	VTM_VOLUME_UNMUTE_IND                      = 2,		
//	VTM_VOLUME_UP_IND                          = 3,
//	VTM_VOLUME_DOWN_IND                        = 4,

	VTM_VOLUME_CTRL_IND_MAX,
};

enum amsVtmEventNoticeCode
{
	AMS_VTM_EVENT_NOTICE_RSVD                  = 0,

	AMS_VTM_CUSTOMER_SCORING                   = 1,
	AMS_VTM_SCREEN_SHARE_EVENT_REPORT          = 2,
	AMS_VTM_SNAP_EVENT_REPORT                  = 3,
	AMS_VTM_SNAP_FILE_UPLOAD                   = 4,
	AMS_VTM_FILE_UPLOAD                        = 5,
	AMS_VTM_FILE_DOWNLOAD                      = 6,
	AMS_VTM_CANCEL_RECV_FILE                   = 7,
	
	AMS_VTM_EVENT_NOTICE_MAX,
};

enum amsVtmEventIndCode
{
	AMS_VTM_EVENT_IND_RSVD                     = 0,

	AMS_VTM_SCREEN_SHARE_ABORT                 = 1,	
	AMS_VTM_REMOTE_CANCEL_RECV_FILE            = 2,

	AMS_VTM_EVENT_IND_MAX,
};

enum cmsCallEventNoticeCode
{
	CMS_CALL_EVENT_NOTICE_RSVD                  = 0,
		
	CMS_CALL_EVENT_NOTICE_VTA_ANSWER            = 1,
	CMS_CALL_EVENT_NOTICE_VTA_RELEASE           = 2,
	CMS_CALL_EVENT_NOTICE_VTA_HOLD              = 3,
	CMS_CALL_EVENT_NOTICE_VTA_UNHOLD            = 4,
	CMS_CALL_EVENT_NOTICE_INNER_CALL_ANSWER     = 5,
	CMS_CALL_EVENT_NOTICE_INNER_CALL_RELEASE    = 6,
	CMS_CALL_EVENT_NOTICE_MONITOR_CALL_ANSWER   = 7,
	CMS_CALL_EVENT_NOTICE_MONITOR_CALL_RELEASE  = 8,
	CMS_CALL_EVENT_NOTICE_VTM_RELEASE           = 9,
	CMS_CALL_EVENT_NOTICE_DEQUEUE               = 10,
	
	CMS_CALL_EVENT_NOTICE_MAX,
};

enum cmsCallEventIndCode
{
	CMS_CALL_EVENT_IND_RSVD                     = 0x00,

	CMS_CALL_EVENT_IND_VTA_OFFLINE              = 0x01,
	CMS_CALL_EVENT_IND_VTA_FORCE_LOGIN_OFFLINE  = 0x02,	
	CMS_CALL_EVENT_IND_VTA_LOGOUT_OFFLINE       = 0x03,  
	CMS_CALL_EVENT_IND_VTA_CALL_STATE_ABORT     = 0x04,
	
	CMS_CALL_EVENT_IND_CALL_TRANSFER            = 0x10,

	CMS_CALL_EVENT_IND_VTM_OFFLINE              = 0x20,
	CMS_CALL_EVENT_IND_VTM_FORCE_LOGIN_OFFLINE  = 0x21,
	CMS_CALL_EVENT_IND_VTM_LOGOUT_OFFLINE       = 0x22,
	
	CMS_CALL_EVENT_IND_VTM_OFFLINE_DEQUEUE      = 0x30,
	CMS_CALL_EVENT_IND_VTM_FORCE_LOGIN_DEQUEUE  = 0x31,
	CMS_CALL_EVENT_IND_VTM_LOGOUT_DEQUEUE       = 0x32,

	CMS_CALL_EVENT_IND_MNG_REL_VTA              = 0x40,
	CMS_CALL_EVENT_IND_MNG_FORCE_LOGOUT_VTA     = 0x41,
	CMS_CALL_EVENT_IND_MNG_DEL_VTA              = 0x42,
	CMS_CALL_EVENT_IND_MNG_FORCE_REL_CALL_VTA   = 0x43,	
	
	CMS_CALL_EVENT_IND_MAX,
};


enum amsScreenShareEventNoticeCode
{
	AMS_SCREEN_SHARE_EVENT_NOTICE_RSVD          = 0,

	AMS_SCREEN_SHARE_ABORT_NOTICE               = 1,

	
	AMS_SCREEN_SHARE_EVENT_NOTICE_MAX,
};


enum amsScreenShareEventIndCode
{
	AMS_SCREEN_SHARE_EVENT_IND_RSVD            = 0,

	AMS_SCREEN_SHARE_ABORT_IND                 = 1,

	
	AMS_SCREEN_SHARE_EVENT_IND_MAX,
};

enum amsVtcTellerState
{	
	AMS_VTC_TELLER_STATE_IDLE                  = 0,
	AMS_VTC_TELLER_STATE_QUEUING               = 1,		
	AMS_VTC_TELLER_STATE_RINGING               = 2,
	AMS_VTC_TELLER_STATE_ANSWER                = 3,
	AMS_VTC_TELLER_STATE_BUSY                  = 4,
	AMS_VTC_TELLER_STATE_PREPARE               = 5,
	AMS_VTC_TELLER_STATE_REST                  = 6,
	AMS_VTC_TELLER_STATE_OFFLINE               = 7,	
	
	AMS_VTC_TELLER_STATE_RSVD,
};

enum amsDbDataItem
{	
	AMS_DB_DATA_ITEM_NULL                      = 0,

	AMS_DB_TELLER_STATE                        = 1,		
	AMS_DB_TELLER_SERIAL_STATE                 = 2,
	AMS_DB_VTM_STATE                           = 3,
	AMS_DB_SERVICE_DETAIL_REPORT               = 4,
	
	AMS_DB_DATA_ITEM_RSVD,
};

enum amsTllerStateItem
{	
	AMS_TELLER_STATE_ITEM_BASE                 = 0,
	AMS_TELLER_AUDIO_REC_STATE                 = 1,		
	AMS_TELLER_SCREEN_REC_STATE                = 2,
	AMS_TELLER_REMOTE_COOP_STATE               = 3,
	AMS_TELLER_SNAP_STATE                      = 4,
	
	AMS_TELLER_STATE_ITEM_RSVD,
};

enum amsSDRItem
{	
	AMS_SDR_ITEM_BASE                          = 0,
	AMS_SDR_TELLER_NETFLOW                     = 1,		
	AMS_SDR_VTM_NETFLOW                        = 2,
	
	AMS_SDR_ITEM_RSVD,
};

enum amsStatType_t
{
	AMS_STAT_TYPE_NULL = 0,

	AMS_MSG_STAT_TYPE,
	AMS_TIMER_STAT_TYPE,
	AMS_QUEUE_SYSTEM_STAT_TYPE,
	AMS_SERVICE_STAT_TYPE,
	AMS_TELLER_STAT_TYPE,
	AMS_VTM_STAT_TYPE,
	AMS_RCAS_STAT_TYPE,
	AMS_RESULT_STAT_TYPE,
	
	AMS_STAT_TYPE_MAX,
};

enum amsTellerStatType_t
{
	AMS_TELLER_STAT_TYPE_NULL = 0,

	AMS_TELLER_LOGIN,
	AMS_TELLER_LOGOUT,
	AMS_TELLER_HANDSHAKE,
	
	AMS_TELLER_SET_IDLE,
	AMS_TELLER_SET_BUSY,
	AMS_TELLER_SET_REST,
	AMS_TELLER_SET_CANCEL_REST,	
	AMS_TELLER_SET_PREPARA,
	AMS_TELLER_SET_PREPARA_COMPLETELY,

	AMS_TELLER_CALL_CONNECT,
	AMS_TELLER_CALL_TRANSFER,
	AMS_TELLER_INNER_CALL,
	
	AMS_TELLER_VOLUME_CTRL,
	AMS_TELLER_AUDIO_RECORD,
	AMS_TELLER_SCREEN_RECORD,
	AMS_TELLER_REMOTE_COOPERATE,
	AMS_TELLER_SNAP,

	AMS_TELLER_WORK_INFO_AFTER_LOGINED,
	
	AMS_TELLER_SCORE_INFO,

	AMS_TELLER_LAST_STATE_INFO,

	AMS_TELLER_STAT_TYPE_MAX,
	
};

enum amsVtmStatType_t
{
	AMS_VTM_STAT_TYPE_NULL = 0,

	AMS_VTM_LOGIN,
	AMS_VTM_LOGOUT,
	AMS_VTM_HANDSHAKE,

	AMS_VTM_VOLUME_CTRL,
	AMS_VTM_REMOTE_COOP,	
	AMS_VTM_SNAP,
	
	AMS_VTM_STAT_TYPE_MAX,

};

enum amsSessionStatType_t
{
	AMS_SESS_STAT_TYPE_NULL = 0,

	AMS_SESS_AUDIO_REC,
	AMS_SESS_AUDIO_REC_FAIL,
	
	AMS_SESS_SCREEN_REC,
	AMS_SESS_SCREEN_REC_FAIL,
	
	AMS_SESS_REMOTE_COOP,
	AMS_SESS_REMOTE_COOP_FAIL,

	AMS_SESS_SNAP,
	AMS_SESS_SNAP_FAIL,
	
	AMS_SESS_CUST_SCORE,
	
	AMS_SESS_STAT_TYPE_MAX,

};

enum amsUpdateInsertInfoType_t
{
    TELLERSTATEDBINFO_E = 1,
    VTMSTATEDBINFO_E,
    AMSSDRDBINFO_E,
    TELLERRNFDBINFO_E,
    VTMRNFDBINFO_E,
};

enum amsUpdateRcasCncrNumType_t
{
	AMS_INCREASE_RCAS_CNCR_NUM = 0,
	AMS_DECREASE_RCAS_CNCR_NUM,
};

enum amsSelectVtaMode_t
{
	AMS_COMMON_SELECT_VTA = 0,
	AMS_SELECT_VTA_PREFER_ORG,
};

#endif//AMSENUM_H


